local _, ConsumableHelper = ...

-------------------------------------------------------------------------------
-- Auto-generated by consumablehelper_scraper — do not edit manually
-- Generated: 2026-08-13T12:39:31.820Z
-------------------------------------------------------------------------------

-- Spec ID constants
local MAGE_ARCANE = 62
local MAGE_FIRE = 63
local MAGE_FROST = 64
local PALADIN_HOLY = 65
local PALADIN_PROTECTION = 66
local PALADIN_RETRIBUTION = 70
local WARRIOR_ARMS = 71
local WARRIOR_FURY = 72
local WARRIOR_PROT = 73
local DRUID_BALANCE = 102
local DRUID_FERAL = 103
local DRUID_GUARDIAN = 104
local DRUID_RESTORATION = 105
local DEATHKNIGHT_BLOOD = 250
local DEATHKNIGHT_FROST_DK = 251
local DEATHKNIGHT_UNHOLY = 252
local HUNTER_BEAST_MASTERY = 253
local HUNTER_MARKSMANSHIP = 254
local HUNTER_SURVIVAL = 255
local PRIEST_DISCIPLINE = 256
local PRIEST_HOLY = 257
local PRIEST_SHADOW = 258
local ROGUE_ASSASSINATION = 259
local ROGUE_OUTLAW = 260
local ROGUE_SUBTLETY = 261
local SHAMAN_ELEMENTAL = 262
local SHAMAN_ENHANCEMENT = 263
local SHAMAN_RESTORATION = 264
local WARLOCK_AFFLICTION = 265
local WARLOCK_DEMONOLOGY = 266
local WARLOCK_DESTRUCTION = 267
local MONK_BREWMASTER = 268
local MONK_WINDWALKER = 269
local MONK_MISTWEAVER = 270
local DEMONHUNTER_HAVOC = 577
local DEMONHUNTER_VENGEANCE = 581
local EVOKER_DEVASTATION = 1467
local EVOKER_PRESERVATION = 1468
local EVOKER_AUGMENTATION = 1473
local DEMONHUNTER_DEVOURER = 1480

-- Class and spec name mappings for command parsing
ConsumableHelper.ClassSpecs = {
    ["warrior"] = {
        ["arms"] = WARRIOR_ARMS,
        ["fury"] = WARRIOR_FURY,
        ["protection"] = WARRIOR_PROT,
    },
    ["paladin"] = {
        ["holy"] = PALADIN_HOLY,
        ["protection"] = PALADIN_PROTECTION,
        ["retribution"] = PALADIN_RETRIBUTION,
    },
    ["hunter"] = {
        ["beastmastery"] = HUNTER_BEAST_MASTERY,
        ["marksmanship"] = HUNTER_MARKSMANSHIP,
        ["survival"] = HUNTER_SURVIVAL,
    },
    ["rogue"] = {
        ["assassination"] = ROGUE_ASSASSINATION,
        ["outlaw"] = ROGUE_OUTLAW,
        ["subtlety"] = ROGUE_SUBTLETY,
    },
    ["priest"] = {
        ["discipline"] = PRIEST_DISCIPLINE,
        ["holy"] = PRIEST_HOLY,
        ["shadow"] = PRIEST_SHADOW,
    },
    ["deathknight"] = {
        ["blood"] = DEATHKNIGHT_BLOOD,
        ["frost"] = DEATHKNIGHT_FROST_DK,
        ["unholy"] = DEATHKNIGHT_UNHOLY,
    },
    ["shaman"] = {
        ["elemental"] = SHAMAN_ELEMENTAL,
        ["enhancement"] = SHAMAN_ENHANCEMENT,
        ["restoration"] = SHAMAN_RESTORATION,
    },
    ["mage"] = {
        ["arcane"] = MAGE_ARCANE,
        ["fire"] = MAGE_FIRE,
        ["frost"] = MAGE_FROST,
    },
    ["warlock"] = {
        ["affliction"] = WARLOCK_AFFLICTION,
        ["demonology"] = WARLOCK_DEMONOLOGY,
        ["destruction"] = WARLOCK_DESTRUCTION,
    },
    ["monk"] = {
        ["brewmaster"] = MONK_BREWMASTER,
        ["windwalker"] = MONK_WINDWALKER,
        ["mistweaver"] = MONK_MISTWEAVER,
    },
    ["druid"] = {
        ["balance"] = DRUID_BALANCE,
        ["feral"] = DRUID_FERAL,
        ["guardian"] = DRUID_GUARDIAN,
        ["restoration"] = DRUID_RESTORATION,
    },
    ["demonhunter"] = {
        ["havoc"] = DEMONHUNTER_HAVOC,
        ["vengeance"] = DEMONHUNTER_VENGEANCE,
        ["devourer"] = DEMONHUNTER_DEVOURER,
    },
    ["evoker"] = {
        ["devastation"] = EVOKER_DEVASTATION,
        ["preservation"] = EVOKER_PRESERVATION,
        ["augmentation"] = EVOKER_AUGMENTATION,
    },
}

-- Available data sources (ordered)
ConsumableHelper.AvailableSources = {
    "wowhead",
    "icyveins",
}

ConsumableHelper.SourceLabels = {
    ["wowhead"] = "Wowhead",
    ["icyveins"] = "Icy Veins",
}

ConsumableHelper.SourceData = {
    ["wowhead"] = {
        ConsumableData = {
            ---------------------------------------------------------------------------
            -- Consumables
            ---------------------------------------------------------------------------
            {
                category = "Consumables",
                items = {
                    { name = "Flask of the Blood Knights", itemId = 241324,
                      qualities = { 241324, 241325 },
                      specs = { DEATHKNIGHT_BLOOD, DEMONHUNTER_DEVOURER, DRUID_BALANCE, DRUID_GUARDIAN, DRUID_RESTORATION, EVOKER_DEVASTATION, EVOKER_PRESERVATION, MAGE_ARCANE, MAGE_FIRE, MONK_MISTWEAVER, MONK_WINDWALKER, PALADIN_PROTECTION, PRIEST_DISCIPLINE, PRIEST_SHADOW, ROGUE_ASSASSINATION, ROGUE_OUTLAW, SHAMAN_ENHANCEMENT, WARLOCK_AFFLICTION, WARRIOR_ARMS, WARRIOR_FURY, WARRIOR_PROT } },
                    { name = "Flask of the Shattered Sun", itemId = 241326,
                      qualities = { 241326, 241327 },
                      specs = { DEATHKNIGHT_BLOOD, DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DEMONHUNTER_HAVOC, DEMONHUNTER_DEVOURER, DRUID_BALANCE, DRUID_FERAL, EVOKER_DEVASTATION, HUNTER_MARKSMANSHIP, MONK_BREWMASTER, MONK_MISTWEAVER, PRIEST_HOLY, ROGUE_OUTLAW, ROGUE_SUBTLETY, SHAMAN_ELEMENTAL, SHAMAN_RESTORATION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION, WARRIOR_ARMS } },
                    { name = "Potion of Recklessness", itemId = 241288,
                      qualities = { 241288, 241289 },
                      specs = { DEATHKNIGHT_BLOOD, DEATHKNIGHT_UNHOLY, DEMONHUNTER_HAVOC, DEMONHUNTER_VENGEANCE, DEMONHUNTER_DEVOURER, DRUID_BALANCE, DRUID_FERAL, DRUID_RESTORATION, EVOKER_DEVASTATION, EVOKER_PRESERVATION, EVOKER_AUGMENTATION, HUNTER_BEAST_MASTERY, HUNTER_MARKSMANSHIP, MAGE_FROST, MONK_MISTWEAVER, MONK_WINDWALKER, PALADIN_HOLY, PALADIN_RETRIBUTION, PRIEST_DISCIPLINE, PRIEST_HOLY, PRIEST_SHADOW, ROGUE_SUBTLETY, SHAMAN_ENHANCEMENT, SHAMAN_RESTORATION, WARRIOR_ARMS, WARRIOR_FURY } },
                    { name = "Concentrated Silvermoon Health Potion", itemId = 271884,
                      qualities = { 271883, 271884 },
                      specs = { DEATHKNIGHT_BLOOD, DEMONHUNTER_HAVOC, DEMONHUNTER_VENGEANCE, DEMONHUNTER_DEVOURER, DRUID_BALANCE, DRUID_FERAL, DRUID_GUARDIAN, DRUID_RESTORATION, EVOKER_DEVASTATION, EVOKER_PRESERVATION, EVOKER_AUGMENTATION, HUNTER_BEAST_MASTERY, HUNTER_MARKSMANSHIP, HUNTER_SURVIVAL, MAGE_ARCANE, MAGE_FIRE, MAGE_FROST, MONK_BREWMASTER, MONK_MISTWEAVER, PALADIN_HOLY, PALADIN_PROTECTION, PRIEST_DISCIPLINE, PRIEST_HOLY, PRIEST_SHADOW, ROGUE_ASSASSINATION, ROGUE_OUTLAW, ROGUE_SUBTLETY, SHAMAN_ENHANCEMENT, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION, WARRIOR_ARMS, WARRIOR_FURY, WARRIOR_PROT } },
                    { name = "Void-Touched Augment Rune", itemId = 259085 },
                    { name = "Blooming Feast", itemId = 242273,
                      specs = { DEATHKNIGHT_BLOOD, DEMONHUNTER_VENGEANCE, DRUID_FERAL, PRIEST_SHADOW, WARRIOR_ARMS, WARRIOR_FURY } },
                    { name = "Gebbo's Bottomless Bag", itemId = 270164,
                      specs = { DEATHKNIGHT_BLOOD } },
                    { name = "Light's Potential", itemId = 241308,
                      qualities = { 241308, 241309 },
                      specs = { DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DEMONHUNTER_VENGEANCE, DRUID_BALANCE, DRUID_FERAL, DRUID_GUARDIAN, EVOKER_DEVASTATION, HUNTER_BEAST_MASTERY, HUNTER_MARKSMANSHIP, MAGE_ARCANE, MAGE_FIRE, MAGE_FROST, MONK_BREWMASTER, PALADIN_PROTECTION, PALADIN_RETRIBUTION, PRIEST_DISCIPLINE, PRIEST_HOLY, ROGUE_ASSASSINATION, ROGUE_SUBTLETY, SHAMAN_ELEMENTAL, SHAMAN_ENHANCEMENT, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION, WARRIOR_ARMS, WARRIOR_FURY, WARRIOR_PROT } },
                    { name = "Silvermoon Health Potion", itemId = 241304,
                      qualities = { 241305, 241304 },
                      specs = { DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DRUID_FERAL, DRUID_RESTORATION, EVOKER_DEVASTATION, EVOKER_PRESERVATION, MAGE_FIRE, MONK_BREWMASTER, SHAMAN_RESTORATION } },
                    { name = "Thalassian Phoenix Oil", itemId = 243734,
                      qualities = { 243733, 243734 },
                      specs = { DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DEMONHUNTER_HAVOC, DEMONHUNTER_VENGEANCE, DEMONHUNTER_DEVOURER, DRUID_FERAL, DRUID_GUARDIAN, DRUID_RESTORATION, EVOKER_DEVASTATION, EVOKER_PRESERVATION, EVOKER_AUGMENTATION, HUNTER_BEAST_MASTERY, HUNTER_MARKSMANSHIP, HUNTER_SURVIVAL, MAGE_ARCANE, MAGE_FIRE, MAGE_FROST, MONK_BREWMASTER, MONK_MISTWEAVER, MONK_WINDWALKER, PALADIN_HOLY, PALADIN_PROTECTION, PALADIN_RETRIBUTION, PRIEST_DISCIPLINE, PRIEST_HOLY, PRIEST_SHADOW, ROGUE_ASSASSINATION, ROGUE_OUTLAW, ROGUE_SUBTLETY, SHAMAN_ELEMENTAL, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION, WARRIOR_ARMS, WARRIOR_FURY, WARRIOR_PROT } },
                    { name = "Royal Roast", itemId = 242275,
                      specs = { DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DEMONHUNTER_HAVOC, DRUID_FERAL, DRUID_RESTORATION, EVOKER_PRESERVATION, MONK_BREWMASTER, MONK_WINDWALKER, PALADIN_RETRIBUTION, PRIEST_HOLY, PRIEST_SHADOW, ROGUE_SUBTLETY, SHAMAN_ENHANCEMENT, SHAMAN_RESTORATION, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION } },
                    { name = "Flask of the Blood Knights", itemId = 241325,
                      qualities = { 241324, 241325 },
                      specs = { DEMONHUNTER_VENGEANCE } },
                    { name = "Feast of Knowledge", itemId = 275266,
                      specs = { DEMONHUNTER_DEVOURER, HUNTER_BEAST_MASTERY } },
                    { name = "Impossibly Royal Roast", itemId = 255847,
                      specs = { DRUID_BALANCE, MONK_BREWMASTER, MONK_WINDWALKER } },
                    { name = "Venom-Spiced Cutlets", itemId = 275258,
                      specs = { HUNTER_BEAST_MASTERY } },
                    { name = "Fleeting Flask of the Magisters", itemId = 245933,
                      qualities = { 245932, 245933 },
                      specs = { HUNTER_SURVIVAL } },
                    { name = "Loa's Gathering", itemId = 275265,
                      specs = { HUNTER_SURVIVAL } },
                    { name = "Argentleaf Tea", itemId = 242298,
                      specs = { MAGE_FROST, MONK_MISTWEAVER } },
                    { name = "Azeroot Tea", itemId = 242301,
                      specs = { MAGE_FROST, MONK_MISTWEAVER } },
                    { name = "Void-Shrouded Tincture", itemId = 241302,
                      qualities = { 241302, 241303 },
                      specs = { MONK_MISTWEAVER } },
                    { name = "Concentrated Silvermoon Health Potion", itemId = 271883,
                      qualities = { 271883, 271884 },
                      specs = { MONK_WINDWALKER, PALADIN_RETRIBUTION, SHAMAN_ELEMENTAL, SHAMAN_RESTORATION } },
                    { name = "Light's Potential", itemId = 241309,
                      qualities = { 241308, 241309 },
                      specs = { ROGUE_OUTLAW } },
                },
            },
            ---------------------------------------------------------------------------
            -- Flask
            ---------------------------------------------------------------------------
            {
                category = "Flask",
                items = {
                    { name = "Flask of Thalassian Resistance", itemId = 241320,
                      qualities = { 241320, 241321 },
                      specs = { DEATHKNIGHT_BLOOD, DRUID_BALANCE, MAGE_FIRE, MONK_BREWMASTER } },
                    { name = "Fleeting Flask of the Blood Knights", itemId = 245931,
                      qualities = { 245930, 245931 },
                      specs = { ROGUE_SUBTLETY } },
                },
            },
            ---------------------------------------------------------------------------
            -- Food
            ---------------------------------------------------------------------------
            {
                category = "Food",
                items = {
                    { name = "Harandar Celebration", itemId = 255846,
                      specs = { DEATHKNIGHT_BLOOD, DEMONHUNTER_VENGEANCE, DRUID_FERAL, DRUID_GUARDIAN, DRUID_RESTORATION, EVOKER_DEVASTATION, EVOKER_PRESERVATION, HUNTER_MARKSMANSHIP, MAGE_FIRE, MAGE_FROST, MONK_BREWMASTER, MONK_WINDWALKER, PALADIN_PROTECTION, PALADIN_RETRIBUTION, PRIEST_DISCIPLINE, PRIEST_HOLY, ROGUE_OUTLAW, SHAMAN_ELEMENTAL, WARLOCK_AFFLICTION, WARLOCK_DESTRUCTION, WARRIOR_PROT } },
                    { name = "Hearty Silvermoon Parade", itemId = 266985,
                      specs = { DEATHKNIGHT_FROST_DK, EVOKER_AUGMENTATION, MONK_BREWMASTER, PALADIN_HOLY } },
                    { name = "Hearty Harandar Celebration", itemId = 266996,
                      specs = { DEMONHUNTER_HAVOC, MONK_MISTWEAVER, PALADIN_HOLY } },
                    { name = "Quel'dorei Medley", itemId = 242272,
                      specs = { DEMONHUNTER_VENGEANCE, EVOKER_DEVASTATION, MAGE_FIRE } },
                    { name = "Champion's Bento", itemId = 242274,
                      specs = { DEMONHUNTER_VENGEANCE, DEMONHUNTER_DEVOURER, DRUID_BALANCE, EVOKER_DEVASTATION, MAGE_FIRE, MAGE_FROST, MONK_BREWMASTER, WARRIOR_ARMS, WARRIOR_FURY } },
                    { name = "Flora Frenzy", itemId = 255848,
                      specs = { DEMONHUNTER_VENGEANCE, PRIEST_DISCIPLINE, WARRIOR_ARMS, WARRIOR_FURY } },
                    { name = "Jester's Board", itemId = 222730,
                      specs = { DEMONHUNTER_VENGEANCE } },
                    { name = "Beledar's Bounty", itemId = 222728,
                      specs = { DEMONHUNTER_VENGEANCE } },
                    { name = "Crimson Calamari", itemId = 242277,
                      specs = { DRUID_FERAL } },
                    { name = "Alchemical Flavor Pocket", itemId = 200652,
                      specs = { MONK_MISTWEAVER } },
                    { name = "Hearty Impossibly Royal Roast", itemId = 268679,
                      specs = { MONK_MISTWEAVER, PALADIN_HOLY } },
                },
            },
            ---------------------------------------------------------------------------
            -- Combat Potions
            ---------------------------------------------------------------------------
            {
                category = "Combat Potions",
                items = {
                    { name = "Draught of Rampant Abandon", itemId = 241292,
                      qualities = { 241292, 241293 },
                      specs = { DEATHKNIGHT_FROST_DK, DEMONHUNTER_VENGEANCE, DRUID_FERAL, DRUID_GUARDIAN, MONK_BREWMASTER, PALADIN_PROTECTION, ROGUE_SUBTLETY, WARRIOR_ARMS, WARRIOR_FURY, WARRIOR_PROT } },
                    { name = "Vantus Rune: Radiant", itemId = 245880,
                      qualities = { 245879, 245880 },
                      specs = { MAGE_FROST } },
                    { name = "Voidlight Potion Cauldron", itemId = 241284,
                      qualities = { 241284, 241285 },
                      specs = { MONK_BREWMASTER, SHAMAN_ENHANCEMENT } },
                    { name = "Void-Shrouded Tincture", itemId = 241303,
                      qualities = { 241302, 241303 },
                      specs = { PRIEST_DISCIPLINE, PRIEST_HOLY } },
                },
            },
            ---------------------------------------------------------------------------
            -- Consumables for Death Knights
            ---------------------------------------------------------------------------
            {
                category = "Consumables for Death Knights",
                items = {
                    { name = "Flask of the Magisters", itemId = 241322,
                      qualities = { 241322, 241323 },
                      specs = { DEATHKNIGHT_UNHOLY, DEMONHUNTER_HAVOC, DEMONHUNTER_DEVOURER, DRUID_BALANCE, DRUID_FERAL, EVOKER_DEVASTATION, EVOKER_PRESERVATION, EVOKER_AUGMENTATION, HUNTER_BEAST_MASTERY, MAGE_FIRE, MAGE_FROST, MONK_BREWMASTER, PALADIN_HOLY, PALADIN_RETRIBUTION, PRIEST_SHADOW, ROGUE_SUBTLETY, SHAMAN_ELEMENTAL, SHAMAN_ENHANCEMENT, WARLOCK_AFFLICTION, WARRIOR_FURY } },
                    { name = "Refulgent Whetstone", itemId = 237371,
                      qualities = { 237370, 237371 },
                      specs = { DEATHKNIGHT_UNHOLY } },
                    { name = "Refulgent Weightstone", itemId = 237369,
                      specs = { DEATHKNIGHT_UNHOLY } },
                    { name = "Silvermoon Parade", itemId = 255845,
                      specs = { DEATHKNIGHT_UNHOLY, DEMONHUNTER_VENGEANCE, DRUID_GUARDIAN, HUNTER_MARKSMANSHIP, MAGE_ARCANE, MONK_BREWMASTER, MONK_WINDWALKER, PALADIN_PROTECTION, ROGUE_ASSASSINATION, ROGUE_SUBTLETY, SHAMAN_ENHANCEMENT, SHAMAN_RESTORATION, WARLOCK_DEMONOLOGY, WARRIOR_PROT } },
                    { name = "Powerful Eversong Diamond", itemId = 240966,
                      qualities = { 240966, 240967 },
                      specs = { DEATHKNIGHT_UNHOLY } },
                },
            },
            ---------------------------------------------------------------------------
            -- Consumables in Midnight
            ---------------------------------------------------------------------------
            {
                category = "Consumables in Midnight",
                items = {
                    { name = "Sanguithorn Tea", itemId = 242299,
                      specs = { DRUID_FERAL, EVOKER_DEVASTATION, MAGE_FROST, MONK_MISTWEAVER, PALADIN_HOLY, SHAMAN_RESTORATION } },
                },
            },
            ---------------------------------------------------------------------------
            -- Consumables for Druid
            ---------------------------------------------------------------------------
            {
                category = "Consumables for Druid",
                items = {
                    { name = "Lightfused Mana Potion", itemId = 241300,
                      qualities = { 241300, 241301 },
                      specs = { DRUID_RESTORATION, EVOKER_PRESERVATION, MONK_MISTWEAVER, PALADIN_HOLY, SHAMAN_RESTORATION } },
                },
            },
            ---------------------------------------------------------------------------
            -- Gems and Enchants
            ---------------------------------------------------------------------------
            {
                category = "Gems and Enchants",
                items = {
                    { name = "Enchant Weapon - Arcane Mastery", itemId = 244031,
                      qualities = { 244030, 244031 },
                      specs = { EVOKER_AUGMENTATION } },
                    { name = "Enchant Helm - Empowered Rune of Avoidance", itemId = 244007,
                      qualities = { 244006, 244007 },
                      specs = { EVOKER_AUGMENTATION } },
                    { name = "Enchant Shoulders - Amirdrassil's Grace", itemId = 243991,
                      qualities = { 243990, 243991 },
                      specs = { EVOKER_AUGMENTATION } },
                    { name = "Enchant Chest - Mark of the Worldsoul", itemId = 243977,
                      qualities = { 243976, 243977 },
                      specs = { EVOKER_AUGMENTATION } },
                    { name = "Sunfire Silk Spellthread", itemId = 240133,
                      specs = { EVOKER_AUGMENTATION } },
                    { name = "Enchant Boots - Lynx's Dexterity", itemId = 243953,
                      qualities = { 243952, 243953 },
                      specs = { EVOKER_AUGMENTATION } },
                    { name = "Enchant Ring - Zul'jin's Mastery", itemId = 243959,
                      qualities = { 243958, 243959 },
                      specs = { EVOKER_AUGMENTATION } },
                    { name = "Indecipherable Eversong Diamond", itemId = 240983,
                      qualities = { 240982, 240983 },
                      specs = { EVOKER_AUGMENTATION } },
                    { name = "Flawless Deadly Amethyst", itemId = 240898,
                      qualities = { 240897, 240898 },
                      specs = { EVOKER_AUGMENTATION } },
                },
            },
            ---------------------------------------------------------------------------
            -- Augment Rune
            ---------------------------------------------------------------------------
            {
                category = "Augment Rune",
                items = {
                    { name = "Ethereal Augment Rune", itemId = 243191,
                      specs = { MAGE_FROST } },
                    { name = "Soulgorged Augment Rune", itemId = 246492,
                      specs = { MAGE_FROST } },
                },
            },
            ---------------------------------------------------------------------------
            -- Flasks
            ---------------------------------------------------------------------------
            {
                category = "Flasks",
                items = {
                    { name = "Cauldron of Sin'dorei Flasks", itemId = 241318,
                      qualities = { 241318, 241319 },
                      specs = { MONK_BREWMASTER, SHAMAN_ENHANCEMENT } },
                },
            },
            ---------------------------------------------------------------------------
            -- Further Consumables
            ---------------------------------------------------------------------------
            {
                category = "Further Consumables",
                items = {
                    { name = "Void-Touched Drums", itemId = 244639,
                      specs = { MONK_BREWMASTER } },
                    { name = "Emergency Soul Link", itemId = 269586,
                      qualities = { 248486, 269586 },
                      specs = { MONK_BREWMASTER } },
                },
            },
            ---------------------------------------------------------------------------
            -- Mana Water
            ---------------------------------------------------------------------------
            {
                category = "Mana Water",
                items = {
                    { name = "Mana Lily Tea", itemId = 242297,
                      specs = { MONK_MISTWEAVER } },
                    { name = "Tranquility Bloom Tea", itemId = 242300,
                      specs = { MONK_MISTWEAVER } },
                },
            },
        },
        EnchantData = {
            ---------------------------------------------------------------------------
            -- Gems and Enchants
            ---------------------------------------------------------------------------
            {
                category = "Gems and Enchants",
                items = {
                    { name = "Enchant Helm - Empowered Blessing of Speed", itemId = 243981,
                      qualities = { 243980, 243981 },
                      specs = { DEATHKNIGHT_BLOOD, DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DEMONHUNTER_VENGEANCE, DRUID_GUARDIAN, MONK_BREWMASTER, PALADIN_PROTECTION, WARRIOR_PROT } },
                    { name = "Enchant Shoulders - Akil'zon's Swiftness", itemId = 243963,
                      qualities = { 243962, 243963 },
                      specs = { DEATHKNIGHT_BLOOD, DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DEMONHUNTER_VENGEANCE, DRUID_GUARDIAN, MONK_BREWMASTER, PALADIN_PROTECTION, PRIEST_SHADOW, WARRIOR_PROT } },
                    { name = "Enchant Chest - Mark of the Worldsoul", itemId = 243977,
                      qualities = { 243976, 243977 },
                      specs = { DEATHKNIGHT_BLOOD, DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DEMONHUNTER_HAVOC, DEMONHUNTER_VENGEANCE, DEMONHUNTER_DEVOURER, DRUID_BALANCE, DRUID_FERAL, DRUID_GUARDIAN, DRUID_RESTORATION, EVOKER_DEVASTATION, EVOKER_PRESERVATION, HUNTER_BEAST_MASTERY, HUNTER_MARKSMANSHIP, HUNTER_SURVIVAL, MAGE_ARCANE, MAGE_FIRE, MAGE_FROST, MONK_BREWMASTER, MONK_MISTWEAVER, MONK_WINDWALKER, PALADIN_PROTECTION, PALADIN_RETRIBUTION, PRIEST_DISCIPLINE, PRIEST_HOLY, PRIEST_SHADOW, ROGUE_ASSASSINATION, ROGUE_OUTLAW, ROGUE_SUBTLETY, SHAMAN_ELEMENTAL, SHAMAN_ENHANCEMENT, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION, WARRIOR_ARMS, WARRIOR_FURY, WARRIOR_PROT } },
                    { name = "Forest Hunter's Armor Kit", itemId = 244641,
                      qualities = { 244640, 244641 },
                      specs = { DEATHKNIGHT_BLOOD, DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DEMONHUNTER_HAVOC, DEMONHUNTER_VENGEANCE, DRUID_FERAL, DRUID_GUARDIAN, HUNTER_BEAST_MASTERY, HUNTER_MARKSMANSHIP, HUNTER_SURVIVAL, MONK_BREWMASTER, MONK_WINDWALKER, PALADIN_PROTECTION, PALADIN_RETRIBUTION, ROGUE_ASSASSINATION, ROGUE_OUTLAW, ROGUE_SUBTLETY, SHAMAN_ENHANCEMENT, WARRIOR_ARMS, WARRIOR_FURY, WARRIOR_PROT } },
                    { name = "Enchant Boots - Farstrider's Hunt", itemId = 244009,
                      qualities = { 244008, 244009 },
                      specs = { DEATHKNIGHT_BLOOD, DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DEMONHUNTER_VENGEANCE, DRUID_GUARDIAN, MONK_BREWMASTER, PALADIN_PROTECTION, WARRIOR_PROT } },
                    { name = "Enchant Ring - Nature's Fury", itemId = 243987,
                      qualities = { 243986, 243987 },
                      specs = { DEATHKNIGHT_BLOOD, EVOKER_DEVASTATION, PRIEST_HOLY } },
                    { name = "Indecipherable Eversong Diamond", itemId = 240983,
                      qualities = { 240982, 240983 },
                      specs = { DEATHKNIGHT_BLOOD, DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DEMONHUNTER_VENGEANCE, DEMONHUNTER_DEVOURER, DRUID_BALANCE, DRUID_GUARDIAN, DRUID_RESTORATION, EVOKER_DEVASTATION, EVOKER_PRESERVATION, HUNTER_MARKSMANSHIP, HUNTER_SURVIVAL, MAGE_FIRE, MONK_BREWMASTER, MONK_MISTWEAVER, MONK_WINDWALKER, PALADIN_HOLY, PALADIN_PROTECTION, PALADIN_RETRIBUTION, PRIEST_DISCIPLINE, PRIEST_HOLY, PRIEST_SHADOW, ROGUE_ASSASSINATION, ROGUE_OUTLAW, ROGUE_SUBTLETY, SHAMAN_ENHANCEMENT, SHAMAN_RESTORATION, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION, WARRIOR_ARMS, WARRIOR_FURY, WARRIOR_PROT } },
                    { name = "Flawless Deadly Peridot", itemId = 240890,
                      qualities = { 240889, 240890 },
                      specs = { DEATHKNIGHT_BLOOD, DEATHKNIGHT_FROST_DK, DEMONHUNTER_HAVOC, DEMONHUNTER_VENGEANCE, EVOKER_DEVASTATION, HUNTER_MARKSMANSHIP, MONK_MISTWEAVER, MONK_WINDWALKER, PRIEST_DISCIPLINE, ROGUE_OUTLAW, WARRIOR_ARMS } },
                    { name = "Enchant Ring - Eyes of the Eagle", itemId = 243957,
                      qualities = { 243956, 243957 },
                      specs = { DEATHKNIGHT_BLOOD, DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DEMONHUNTER_HAVOC, DEMONHUNTER_VENGEANCE, DEMONHUNTER_DEVOURER, DRUID_BALANCE, DRUID_FERAL, HUNTER_BEAST_MASTERY, HUNTER_MARKSMANSHIP, HUNTER_SURVIVAL, MAGE_ARCANE, MAGE_FIRE, MONK_BREWMASTER, MONK_WINDWALKER, PALADIN_RETRIBUTION, PRIEST_SHADOW, ROGUE_ASSASSINATION, ROGUE_OUTLAW, ROGUE_SUBTLETY, SHAMAN_ELEMENTAL, SHAMAN_ENHANCEMENT, SHAMAN_RESTORATION, WARLOCK_AFFLICTION, WARLOCK_DESTRUCTION, WARRIOR_ARMS } },
                    { name = "Enchant Weapon - Jan'alai's Precision", itemId = 243971,
                      qualities = { 243970, 243971 },
                      specs = { DEMONHUNTER_HAVOC, DEMONHUNTER_VENGEANCE, HUNTER_MARKSMANSHIP, ROGUE_OUTLAW, ROGUE_SUBTLETY, SHAMAN_ELEMENTAL, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY } },
                    { name = "Enchant Helm - Empowered Rune of Avoidance", itemId = 244007,
                      qualities = { 244006, 244007 },
                      specs = { DEMONHUNTER_HAVOC, DEMONHUNTER_VENGEANCE, DEMONHUNTER_DEVOURER, DRUID_BALANCE, DRUID_FERAL, EVOKER_DEVASTATION, HUNTER_BEAST_MASTERY, HUNTER_SURVIVAL, MAGE_ARCANE, MAGE_FIRE, MAGE_FROST, MONK_WINDWALKER, PALADIN_RETRIBUTION, PRIEST_SHADOW, ROGUE_SUBTLETY, SHAMAN_ELEMENTAL, SHAMAN_ENHANCEMENT, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION, WARRIOR_ARMS, WARRIOR_FURY } },
                    { name = "Enchant Shoulders - Amirdrassil's Grace", itemId = 243991,
                      qualities = { 243990, 243991 },
                      specs = { DEMONHUNTER_HAVOC, DEMONHUNTER_VENGEANCE, DEMONHUNTER_DEVOURER, DRUID_BALANCE, DRUID_FERAL, EVOKER_DEVASTATION, HUNTER_BEAST_MASTERY, HUNTER_SURVIVAL, MAGE_FIRE, MAGE_FROST, MONK_WINDWALKER, ROGUE_SUBTLETY, SHAMAN_ELEMENTAL, SHAMAN_ENHANCEMENT, WARLOCK_DESTRUCTION, WARRIOR_ARMS, WARRIOR_FURY } },
                    { name = "Enchant Boots - Lynx's Dexterity", itemId = 243953,
                      qualities = { 243952, 243953 },
                      specs = { DEMONHUNTER_HAVOC, DEMONHUNTER_VENGEANCE, DEMONHUNTER_DEVOURER, DRUID_BALANCE, DRUID_FERAL, EVOKER_DEVASTATION, HUNTER_BEAST_MASTERY, HUNTER_SURVIVAL, MAGE_FIRE, MAGE_FROST, MONK_WINDWALKER, PRIEST_SHADOW, ROGUE_SUBTLETY, SHAMAN_ELEMENTAL, SHAMAN_ENHANCEMENT, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION, WARRIOR_ARMS, WARRIOR_FURY } },
                    { name = "Blood Knight's Armor Kit", itemId = 244643,
                      qualities = { 244642, 244643 },
                      specs = { DEMONHUNTER_VENGEANCE, WARRIOR_ARMS, WARRIOR_FURY } },
                    { name = "Enchant Ring - Silvermoon's Alacrity", itemId = 244015,
                      qualities = { 244014, 244015 },
                      specs = { DEMONHUNTER_VENGEANCE, DRUID_GUARDIAN, DRUID_RESTORATION, MONK_MISTWEAVER, PALADIN_PROTECTION, PRIEST_DISCIPLINE, ROGUE_OUTLAW, WARLOCK_DEMONOLOGY, WARRIOR_ARMS, WARRIOR_FURY, WARRIOR_PROT } },
                    { name = "Flawless Versatile Peridot", itemId = 240894,
                      qualities = { 240893, 240894 },
                      specs = { DEMONHUNTER_VENGEANCE, DRUID_GUARDIAN, PALADIN_PROTECTION, WARRIOR_PROT } },
                    { name = "Sunfire Silk Spellthread", itemId = 240133,
                      specs = { DEMONHUNTER_DEVOURER, DRUID_BALANCE, EVOKER_DEVASTATION, MAGE_FIRE, MAGE_FROST, MONK_MISTWEAVER, PRIEST_DISCIPLINE, PRIEST_HOLY, PRIEST_SHADOW, SHAMAN_ELEMENTAL, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION } },
                    { name = "Potion of Recklessness", itemId = 241288,
                      qualities = { 241288, 241289 },
                      specs = { HUNTER_SURVIVAL } },
                    { name = "Formula: Enchant Ring - Eyes of the Eagle", itemId = 256739,
                      specs = { MAGE_FROST } },
                    { name = "Enchant Ring - Silvermoon's Tenacity", itemId = 244017,
                      qualities = { 244016, 244017 },
                      specs = { MONK_BREWMASTER } },
                    { name = "Enchant Chest - Mark of the Magister", itemId = 244003,
                      qualities = { 244002, 244003 },
                      specs = { PALADIN_HOLY, SHAMAN_RESTORATION } },
                    { name = "Telluric Eversong Diamond", itemId = 240969,
                      qualities = { 240968, 240969 },
                      specs = { PALADIN_HOLY } },
                    { name = "Enchant Shoulders - Amirdrassil's Grace", itemId = 243990,
                      qualities = { 243990, 243991 },
                      specs = { PALADIN_RETRIBUTION } },
                    { name = "Enchant Boots - Lynx's Dexterity", itemId = 243952,
                      qualities = { 243952, 243953 },
                      specs = { PALADIN_RETRIBUTION } },
                    { name = "Miasmic Jewelbinder", itemId = 275707,
                      specs = { SHAMAN_ENHANCEMENT } },
                    { name = "Telluric Eversong Diamond", itemId = 240968,
                      qualities = { 240968, 240969 },
                      specs = { SHAMAN_RESTORATION } },
                    { name = "Flawless Versatile Garnet", itemId = 240909,
                      qualities = { 240909, 240910 },
                      specs = { SHAMAN_RESTORATION } },
                    { name = "Flawless Deadly Peridot", itemId = 240889,
                      qualities = { 240889, 240890 },
                      specs = { SHAMAN_RESTORATION } },
                    { name = "Flawless Deadly Lapis", itemId = 240913,
                      qualities = { 240913, 240914 },
                      specs = { SHAMAN_RESTORATION } },
                    { name = "Flawless Deadly Amethyst", itemId = 240897,
                      qualities = { 240897, 240898 },
                      specs = { SHAMAN_RESTORATION } },
                    { name = "Enchant Shoulders - Thalassian Recovery", itemId = 244019,
                      qualities = { 244018, 244019 },
                      specs = { WARRIOR_ARMS, WARRIOR_FURY } },
                    { name = "Enchant Chest - Mark of Nalorakk", itemId = 243947,
                      qualities = { 243946, 243947 },
                      specs = { WARRIOR_ARMS, WARRIOR_FURY } },
                },
            },
            ---------------------------------------------------------------------------
            -- Gems
            ---------------------------------------------------------------------------
            {
                category = "Gems",
                items = {
                    { name = "Flawless Masterful Garnet", itemId = 240908,
                      qualities = { 240907, 240908 },
                      specs = { DEATHKNIGHT_BLOOD, DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DEMONHUNTER_HAVOC, DRUID_BALANCE, DRUID_FERAL, EVOKER_DEVASTATION, HUNTER_BEAST_MASTERY, HUNTER_MARKSMANSHIP, MAGE_ARCANE, MAGE_FROST, PALADIN_HOLY, ROGUE_SUBTLETY, SHAMAN_ELEMENTAL, SHAMAN_ENHANCEMENT } },
                    { name = "Powerful Eversong Diamond", itemId = 240967,
                      qualities = { 240966, 240967 },
                      specs = { DEATHKNIGHT_FROST_DK, DEMONHUNTER_HAVOC, DEMONHUNTER_VENGEANCE, DRUID_FERAL, EVOKER_DEVASTATION, HUNTER_BEAST_MASTERY, HUNTER_MARKSMANSHIP, MAGE_ARCANE, MAGE_FIRE, MAGE_FROST, ROGUE_OUTLAW, SHAMAN_ELEMENTAL, SHAMAN_ENHANCEMENT, WARRIOR_ARMS, WARRIOR_FURY } },
                    { name = "Flawless Deadly Amethyst", itemId = 240898,
                      qualities = { 240897, 240898 },
                      specs = { DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DEMONHUNTER_HAVOC, DEMONHUNTER_DEVOURER, EVOKER_DEVASTATION, HUNTER_BEAST_MASTERY, HUNTER_MARKSMANSHIP, HUNTER_SURVIVAL, MAGE_FROST, MONK_BREWMASTER, PRIEST_SHADOW, ROGUE_OUTLAW, ROGUE_SUBTLETY, SHAMAN_ELEMENTAL, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION } },
                    { name = "Flawless Deadly Lapis", itemId = 240914,
                      qualities = { 240913, 240914 },
                      specs = { DEATHKNIGHT_FROST_DK, DEMONHUNTER_HAVOC, EVOKER_DEVASTATION, HUNTER_MARKSMANSHIP, MONK_BREWMASTER } },
                    { name = "Flawless Quick Lapis", itemId = 240916,
                      qualities = { 240915, 240916 },
                      specs = { DEMONHUNTER_VENGEANCE, MAGE_FIRE, ROGUE_OUTLAW } },
                    { name = "Flawless Quick Garnet", itemId = 240906,
                      qualities = { 240905, 240906 },
                      specs = { DEMONHUNTER_VENGEANCE, EVOKER_DEVASTATION, MAGE_FIRE, MONK_WINDWALKER, PRIEST_SHADOW, ROGUE_ASSASSINATION, ROGUE_OUTLAW, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION, WARRIOR_ARMS } },
                    { name = "Flawless Quick Amethyst", itemId = 240900,
                      qualities = { 240899, 240900 },
                      specs = { DEMONHUNTER_VENGEANCE, DEMONHUNTER_DEVOURER, DRUID_BALANCE, DRUID_FERAL, EVOKER_PRESERVATION, HUNTER_BEAST_MASTERY, HUNTER_SURVIVAL, MAGE_ARCANE, MAGE_FIRE, MONK_WINDWALKER, PALADIN_HOLY, ROGUE_SUBTLETY, SHAMAN_ENHANCEMENT, WARRIOR_FURY } },
                    { name = "Prismatic Focusing Iris", itemId = 251487,
                      qualities = { 251487, 251488 },
                      specs = { DRUID_BALANCE } },
                    { name = "Flawless Masterful Peridot", itemId = 240892,
                      qualities = { 240891, 240892 },
                      specs = { DRUID_BALANCE, DRUID_RESTORATION, HUNTER_BEAST_MASTERY, MAGE_ARCANE, MAGE_FIRE, MAGE_FROST, PALADIN_HOLY, PALADIN_RETRIBUTION, PRIEST_SHADOW, ROGUE_ASSASSINATION, ROGUE_SUBTLETY, SHAMAN_ELEMENTAL, SHAMAN_ENHANCEMENT, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION, WARRIOR_FURY } },
                    { name = "Flawless Masterful Lapis", itemId = 240918,
                      qualities = { 240917, 240918 },
                      specs = { DRUID_BALANCE, DRUID_FERAL, HUNTER_BEAST_MASTERY, MAGE_ARCANE, MAGE_FROST, PALADIN_HOLY, SHAMAN_ELEMENTAL, SHAMAN_ENHANCEMENT } },
                    { name = "Flawless Masterful Peridot", itemId = 240891,
                      qualities = { 240891, 240892 },
                      specs = { DRUID_FERAL } },
                    { name = "Flawless Versatile Garnet", itemId = 240910,
                      qualities = { 240909, 240910 },
                      specs = { MONK_BREWMASTER, PRIEST_HOLY, ROGUE_OUTLAW } },
                    { name = "Loa Worshiper's Band", itemId = 251513,
                      specs = { PALADIN_RETRIBUTION } },
                },
            },
            ---------------------------------------------------------------------------
            -- Weapon Enchant
            ---------------------------------------------------------------------------
            {
                category = "Weapon Enchant",
                items = {
                    { name = "Thalassian Phoenix Oil", itemId = 243734,
                      qualities = { 243733, 243734 },
                      specs = { DEATHKNIGHT_BLOOD } },
                    { name = "Enchant Weapon - Arcane Mastery", itemId = 244031,
                      qualities = { 244030, 244031 },
                      specs = { DEMONHUNTER_HAVOC, DEMONHUNTER_VENGEANCE, DEMONHUNTER_DEVOURER, DRUID_BALANCE, EVOKER_PRESERVATION, HUNTER_BEAST_MASTERY, HUNTER_SURVIVAL, PALADIN_RETRIBUTION, PRIEST_SHADOW, ROGUE_SUBTLETY, SHAMAN_ELEMENTAL, SHAMAN_ENHANCEMENT, WARRIOR_FURY } },
                    { name = "Enchant Weapon - Acuity of the Ren'dorei", itemId = 244029,
                      qualities = { 244028, 244029 },
                      specs = { DEMONHUNTER_VENGEANCE, DRUID_FERAL, EVOKER_DEVASTATION, MAGE_ARCANE, MAGE_FIRE, MAGE_FROST, MONK_BREWMASTER, MONK_MISTWEAVER, MONK_WINDWALKER, PALADIN_HOLY, PRIEST_HOLY, ROGUE_OUTLAW, ROGUE_SUBTLETY, SHAMAN_ENHANCEMENT, SHAMAN_RESTORATION, WARLOCK_DESTRUCTION, WARRIOR_ARMS } },
                    { name = "Enchant Weapon - Berserker's Rage", itemId = 243973,
                      qualities = { 243972, 243973 },
                      specs = { DEMONHUNTER_VENGEANCE, DRUID_GUARDIAN, DRUID_RESTORATION, MONK_MISTWEAVER, PALADIN_PROTECTION, PRIEST_DISCIPLINE, ROGUE_ASSASSINATION, ROGUE_SUBTLETY, SHAMAN_ELEMENTAL, SHAMAN_ENHANCEMENT, WARRIOR_ARMS, WARRIOR_FURY, WARRIOR_PROT } },
                    { name = "Enchant Weapon - Worldsoul Tenacity", itemId = 244001,
                      qualities = { 244000, 244001 },
                      specs = { DEMONHUNTER_VENGEANCE, MONK_BREWMASTER, ROGUE_SUBTLETY } },
                    { name = "Thalassian Phoenix Oil", itemId = 243733,
                      qualities = { 243733, 243734 },
                      specs = { DRUID_BALANCE, SHAMAN_ELEMENTAL } },
                    { name = "Smuggler's Enchanted Edge", itemId = 243737,
                      qualities = { 243737, 243738 },
                      specs = { DRUID_BALANCE } },
                    { name = "Enchant Weapon - Jan'alai's Precision", itemId = 243970,
                      qualities = { 243970, 243971 },
                      specs = { ROGUE_OUTLAW } },
                    { name = "Enchant Weapon - Worldsoul Cradle", itemId = 243997,
                      qualities = { 243996, 243997 },
                      specs = { SHAMAN_RESTORATION } },
                },
            },
            ---------------------------------------------------------------------------
            -- Weapon Buff
            ---------------------------------------------------------------------------
            {
                category = "Weapon Buff",
                items = {
                    { name = "Smuggler's Enchanted Edge", itemId = 243738,
                      qualities = { 243737, 243738 },
                      specs = { DEMONHUNTER_VENGEANCE } },
                    { name = "Refulgent Weightstone", itemId = 237369,
                      specs = { DEMONHUNTER_VENGEANCE } },
                    { name = "Refulgent Whetstone", itemId = 237371,
                      qualities = { 237370, 237371 },
                      specs = { DEMONHUNTER_VENGEANCE } },
                    { name = "Oil of Dawn", itemId = 243736,
                      qualities = { 243735, 243736 },
                      specs = { DRUID_RESTORATION, EVOKER_PRESERVATION } },
                    { name = "Adamantite Sharpening Stone", itemId = 23529,
                      specs = { ROGUE_SUBTLETY } },
                },
            },
            ---------------------------------------------------------------------------
            -- Enchants
            ---------------------------------------------------------------------------
            {
                category = "Enchants",
                items = {
                    { name = "Enchant Helm - Empowered Hex of Leeching", itemId = 243951,
                      qualities = { 243950, 243951 },
                      specs = { DRUID_RESTORATION, EVOKER_PRESERVATION, HUNTER_MARKSMANSHIP, MONK_BREWMASTER, MONK_MISTWEAVER, PALADIN_HOLY, PRIEST_DISCIPLINE, PRIEST_HOLY, ROGUE_ASSASSINATION, ROGUE_OUTLAW, SHAMAN_RESTORATION, WARRIOR_ARMS, WARRIOR_FURY } },
                    { name = "Enchant Shoulders - Silvermoon's Mending", itemId = 244021,
                      qualities = { 244020, 244021 },
                      specs = { DRUID_RESTORATION, EVOKER_PRESERVATION, HUNTER_MARKSMANSHIP, MAGE_ARCANE, MONK_BREWMASTER, MONK_MISTWEAVER, PALADIN_HOLY, PRIEST_DISCIPLINE, PRIEST_HOLY, ROGUE_ASSASSINATION, ROGUE_OUTLAW, SHAMAN_RESTORATION } },
                    { name = "Arcanoweave Spellthread", itemId = 240155,
                      qualities = { 240154, 240155 },
                      specs = { DRUID_RESTORATION, EVOKER_PRESERVATION, MAGE_ARCANE, PALADIN_HOLY, SHAMAN_RESTORATION } },
                    { name = "Enchant Boots - Shaladrassil's Roots", itemId = 243983,
                      qualities = { 243982, 243983 },
                      specs = { DRUID_RESTORATION, EVOKER_PRESERVATION, HUNTER_MARKSMANSHIP, MAGE_ARCANE, MONK_BREWMASTER, MONK_MISTWEAVER, PALADIN_HOLY, PRIEST_DISCIPLINE, PRIEST_HOLY, ROGUE_ASSASSINATION, ROGUE_OUTLAW, SHAMAN_RESTORATION, WARRIOR_ARMS, WARRIOR_FURY } },
                    { name = "Enchant Ring - Zul'jin's Mastery", itemId = 243959,
                      qualities = { 243958, 243959 },
                      specs = { EVOKER_PRESERVATION, PALADIN_HOLY, WARRIOR_FURY } },
                    { name = "Enchant Shoulders - Flight of the Eagle", itemId = 243961,
                      qualities = { 243960, 243961 },
                      specs = { WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY } },
                },
            },
            ---------------------------------------------------------------------------
            -- World of Warcraft Retail & Classic Healing Expert
            ---------------------------------------------------------------------------
            {
                category = "World of Warcraft Retail & Classic Healing Expert",
                items = {
                    { name = "Phial of Static Empowerment", itemId = 191336,
                      qualities = { 191336, 191337 },
                      specs = { EVOKER_PRESERVATION } },
                },
            },
        },
    },
    ["icyveins"] = {
        ConsumableData = {
            ---------------------------------------------------------------------------
            -- Enchants and Weapon Augments
            ---------------------------------------------------------------------------
            {
                category = "Enchants and Weapon Augments",
                items = {
                    { name = "Thalassian Phoenix Oil", itemId = 243733,
                      qualities = { 243733, 243734 } },
                    { name = "Empowered Blessing of Speed", itemId = 243981,
                      qualities = { 243980, 243981 },
                      specs = { DEATHKNIGHT_BLOOD, DRUID_GUARDIAN, EVOKER_AUGMENTATION, MAGE_ARCANE, MAGE_FIRE, MONK_BREWMASTER, PALADIN_PROTECTION, PRIEST_SHADOW, ROGUE_ASSASSINATION, ROGUE_OUTLAW, SHAMAN_ELEMENTAL, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION } },
                    { name = "Akil'zon's Swiftness", itemId = 243962,
                      qualities = { 243962, 243963 },
                      specs = { DEATHKNIGHT_BLOOD, DRUID_GUARDIAN, EVOKER_AUGMENTATION, MAGE_ARCANE, MAGE_FIRE, MONK_BREWMASTER, PALADIN_PROTECTION, PRIEST_SHADOW, SHAMAN_ELEMENTAL, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION, WARRIOR_ARMS, WARRIOR_FURY } },
                    { name = "Mark of the Worldsoul", itemId = 243977,
                      qualities = { 243976, 243977 },
                      specs = { DEATHKNIGHT_BLOOD, DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DEMONHUNTER_HAVOC, DEMONHUNTER_VENGEANCE, DEMONHUNTER_DEVOURER, DRUID_BALANCE, DRUID_FERAL, DRUID_GUARDIAN, DRUID_RESTORATION, EVOKER_DEVASTATION, EVOKER_PRESERVATION, EVOKER_AUGMENTATION, HUNTER_BEAST_MASTERY, HUNTER_MARKSMANSHIP, HUNTER_SURVIVAL, MAGE_ARCANE, MAGE_FIRE, MAGE_FROST, MONK_BREWMASTER, MONK_MISTWEAVER, MONK_WINDWALKER, PALADIN_PROTECTION, PALADIN_RETRIBUTION, PRIEST_HOLY, PRIEST_SHADOW, ROGUE_ASSASSINATION, ROGUE_OUTLAW, ROGUE_SUBTLETY, SHAMAN_ELEMENTAL, SHAMAN_ENHANCEMENT, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION, WARRIOR_ARMS, WARRIOR_FURY, WARRIOR_PROT } },
                    { name = "Forest Hunter's Armor Kit", itemId = 244640,
                      qualities = { 244640, 244641 },
                      specs = { DEATHKNIGHT_BLOOD, DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DEMONHUNTER_HAVOC, DEMONHUNTER_VENGEANCE, DRUID_FERAL, DRUID_GUARDIAN, HUNTER_BEAST_MASTERY, HUNTER_MARKSMANSHIP, HUNTER_SURVIVAL, MONK_BREWMASTER, MONK_WINDWALKER, PALADIN_RETRIBUTION, ROGUE_ASSASSINATION, ROGUE_OUTLAW, ROGUE_SUBTLETY, SHAMAN_ENHANCEMENT } },
                    { name = "Farstrider's Hunt", itemId = 244008,
                      qualities = { 244008, 244009 },
                      specs = { DEATHKNIGHT_BLOOD, DRUID_GUARDIAN, EVOKER_DEVASTATION, EVOKER_AUGMENTATION, MAGE_ARCANE, MAGE_FIRE, MONK_BREWMASTER, PALADIN_PROTECTION, PRIEST_HOLY, PRIEST_SHADOW, ROGUE_ASSASSINATION, ROGUE_OUTLAW, SHAMAN_ELEMENTAL, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION } },
                    { name = "Silvermoon's Tenacity", itemId = 244016,
                      qualities = { 244016, 244017 },
                      specs = { DEATHKNIGHT_BLOOD, MONK_BREWMASTER, PALADIN_PROTECTION } },
                    { name = "Nature's Fury", itemId = 243986,
                      qualities = { 243986, 243987 },
                      specs = { DEATHKNIGHT_BLOOD, MONK_WINDWALKER, PRIEST_HOLY } },
                    { name = "Empowered Rune of Avoidance", itemId = 244007,
                      qualities = { 244006, 244007 },
                      specs = { DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DEMONHUNTER_HAVOC, DEMONHUNTER_DEVOURER, DRUID_BALANCE, DRUID_FERAL, EVOKER_DEVASTATION, HUNTER_BEAST_MASTERY, MAGE_FROST, MONK_WINDWALKER, PALADIN_RETRIBUTION, ROGUE_SUBTLETY, SHAMAN_ELEMENTAL, SHAMAN_ENHANCEMENT } },
                    { name = "Amirdrassil's Grace", itemId = 243990,
                      qualities = { 243990, 243991 },
                      specs = { DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DEMONHUNTER_HAVOC, DEMONHUNTER_DEVOURER, DRUID_BALANCE, DRUID_FERAL, EVOKER_DEVASTATION, HUNTER_BEAST_MASTERY, MAGE_FROST, MONK_WINDWALKER, PALADIN_RETRIBUTION, ROGUE_SUBTLETY, SHAMAN_ELEMENTAL, SHAMAN_ENHANCEMENT } },
                    { name = "Lynx's Dexterity", itemId = 243952,
                      qualities = { 243952, 243953 },
                      specs = { DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DEMONHUNTER_HAVOC, DEMONHUNTER_DEVOURER, DRUID_BALANCE, DRUID_FERAL, HUNTER_BEAST_MASTERY, MAGE_FROST, MONK_WINDWALKER, PALADIN_RETRIBUTION, PRIEST_SHADOW, ROGUE_SUBTLETY, SHAMAN_ELEMENTAL, SHAMAN_ENHANCEMENT, WARRIOR_ARMS, WARRIOR_FURY } },
                    { name = "Eyes of the Eagle", itemId = 243956,
                      qualities = { 243956, 243957 },
                      specs = { DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DEMONHUNTER_HAVOC, DEMONHUNTER_VENGEANCE, DEMONHUNTER_DEVOURER, DRUID_BALANCE, DRUID_FERAL, EVOKER_DEVASTATION, HUNTER_BEAST_MASTERY, HUNTER_MARKSMANSHIP, HUNTER_SURVIVAL, MAGE_ARCANE, MAGE_FIRE, MAGE_FROST, MONK_BREWMASTER, PALADIN_RETRIBUTION, PRIEST_HOLY, PRIEST_SHADOW, ROGUE_ASSASSINATION, ROGUE_OUTLAW, ROGUE_SUBTLETY, SHAMAN_ELEMENTAL, SHAMAN_ENHANCEMENT, SHAMAN_RESTORATION, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION, WARRIOR_ARMS, WARRIOR_FURY } },
                    { name = "Jan'alai's Precision", itemId = 243970,
                      qualities = { 243970, 243971 },
                      specs = { DEMONHUNTER_HAVOC, DEMONHUNTER_VENGEANCE, DRUID_BALANCE, HUNTER_MARKSMANSHIP, MAGE_FROST, PRIEST_HOLY, ROGUE_ASSASSINATION } },
                    { name = "Arcane Mastery", itemId = 244031,
                      qualities = { 244030, 244031 },
                      specs = { DEMONHUNTER_HAVOC, DEMONHUNTER_DEVOURER, DRUID_FERAL, EVOKER_AUGMENTATION, HUNTER_BEAST_MASTERY, HUNTER_SURVIVAL, PALADIN_RETRIBUTION, PRIEST_SHADOW, ROGUE_SUBTLETY, SHAMAN_ELEMENTAL, SHAMAN_ENHANCEMENT } },
                    { name = "Refulgent Whetstone", itemId = 237371,
                      qualities = { 237370, 237371 },
                      specs = { DEMONHUNTER_VENGEANCE } },
                    { name = "Berserker's Rage", itemId = 243973,
                      qualities = { 243972, 243973 },
                      specs = { DEMONHUNTER_VENGEANCE, DRUID_GUARDIAN, PRIEST_DISCIPLINE, PRIEST_SHADOW, ROGUE_ASSASSINATION, SHAMAN_ENHANCEMENT, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION, WARRIOR_ARMS, WARRIOR_FURY, WARRIOR_PROT } },
                    { name = "Worldsoul Tenacity", itemId = 244000,
                      qualities = { 244000, 244001 },
                      specs = { DEMONHUNTER_VENGEANCE, MONK_BREWMASTER } },
                    { name = "Empowered Hex of Leeching", itemId = 243950,
                      qualities = { 243950, 243951 },
                      specs = { DEMONHUNTER_VENGEANCE, DRUID_BALANCE, DRUID_RESTORATION, EVOKER_PRESERVATION, HUNTER_MARKSMANSHIP, HUNTER_SURVIVAL, MONK_BREWMASTER, MONK_MISTWEAVER, PALADIN_HOLY, PRIEST_DISCIPLINE, PRIEST_HOLY, SHAMAN_RESTORATION, WARRIOR_ARMS, WARRIOR_FURY, WARRIOR_PROT } },
                    { name = "Silvermoon's Mending", itemId = 244021,
                      qualities = { 244020, 244021 },
                      specs = { DEMONHUNTER_VENGEANCE, DRUID_BALANCE, DRUID_RESTORATION, EVOKER_PRESERVATION, HUNTER_MARKSMANSHIP, HUNTER_SURVIVAL, MONK_BREWMASTER, MONK_MISTWEAVER, PALADIN_HOLY, PRIEST_DISCIPLINE, PRIEST_HOLY, ROGUE_ASSASSINATION, ROGUE_OUTLAW, SHAMAN_RESTORATION, WARRIOR_PROT } },
                    { name = "Shaladrassil's Roots", itemId = 243983,
                      qualities = { 243982, 243983 },
                      specs = { DEMONHUNTER_VENGEANCE, DRUID_BALANCE, DRUID_RESTORATION, EVOKER_PRESERVATION, HUNTER_MARKSMANSHIP, HUNTER_SURVIVAL, MONK_BREWMASTER, MONK_MISTWEAVER, PALADIN_HOLY, PRIEST_DISCIPLINE, PRIEST_HOLY, SHAMAN_RESTORATION, WARRIOR_PROT } },
                    { name = "Silvermoon's Alacrity", itemId = 244014,
                      qualities = { 244014, 244015 },
                      specs = { DEMONHUNTER_VENGEANCE, DRUID_GUARDIAN, MONK_MISTWEAVER, MONK_WINDWALKER, PALADIN_HOLY, PRIEST_DISCIPLINE, WARRIOR_PROT } },
                    { name = "Blood Knight's Armor Kit", itemId = 244642,
                      qualities = { 244642, 244643 },
                      specs = { DEMONHUNTER_VENGEANCE, DRUID_GUARDIAN, PALADIN_PROTECTION, WARRIOR_ARMS, WARRIOR_FURY, WARRIOR_PROT } },
                    { name = "Sunfire Silk Spellthread", itemId = 240133,
                      specs = { DEMONHUNTER_DEVOURER, DRUID_BALANCE, EVOKER_DEVASTATION, EVOKER_AUGMENTATION, MAGE_FIRE, MAGE_FROST, PRIEST_HOLY, PRIEST_SHADOW, SHAMAN_ELEMENTAL, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION } },
                    { name = "Acuity of the Ren'dorei", itemId = 244029,
                      qualities = { 244028, 244029 },
                      specs = { DRUID_BALANCE, DRUID_RESTORATION, EVOKER_DEVASTATION, EVOKER_PRESERVATION, MAGE_ARCANE, MAGE_FIRE, MONK_BREWMASTER, MONK_MISTWEAVER, MONK_WINDWALKER, PALADIN_HOLY, PALADIN_PROTECTION, PRIEST_HOLY, ROGUE_OUTLAW, SHAMAN_RESTORATION, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION, WARRIOR_PROT } },
                    { name = "Mark of the Rootwarden", itemId = 243974,
                      qualities = { 243974, 243975 },
                      specs = { DRUID_GUARDIAN, MONK_BREWMASTER } },
                    { name = "Arcanoweave Spellthread", itemId = 240155,
                      qualities = { 240154, 240155 },
                      specs = { DRUID_RESTORATION, EVOKER_PRESERVATION, MAGE_ARCANE, MONK_MISTWEAVER, PALADIN_HOLY, PRIEST_DISCIPLINE, PRIEST_HOLY, SHAMAN_RESTORATION } },
                    { name = "+29 Mastery", itemId = 243959,
                      qualities = { 243958, 243959 },
                      specs = { DRUID_RESTORATION, EVOKER_PRESERVATION, EVOKER_AUGMENTATION, PALADIN_HOLY } },
                    { name = "Oil of Dawn", itemId = 243735,
                      qualities = { 243735, 243736 },
                      specs = { EVOKER_PRESERVATION, PALADIN_HOLY } },
                    { name = "Mark of the Magister", itemId = 244002,
                      qualities = { 244002, 244003 },
                      specs = { PALADIN_HOLY, PRIEST_DISCIPLINE, PRIEST_HOLY, PRIEST_SHADOW, SHAMAN_RESTORATION } },
                    { name = "Hex of Leeching", itemId = 243949,
                      qualities = { 243948, 243949 },
                      specs = { PRIEST_HOLY } },
                    { name = "Thalassian Recovery", itemId = 244018,
                      qualities = { 244018, 244019 },
                      specs = { PRIEST_HOLY } },
                    { name = "Blessing of Speed", itemId = 243979,
                      qualities = { 243978, 243979 },
                      specs = { PRIEST_SHADOW } },
                    { name = "Flight of the Eagle", itemId = 243961,
                      qualities = { 243960, 243961 },
                      specs = { PRIEST_SHADOW } },
                    { name = "Bright Linen Spellthread", itemId = 240156,
                      qualities = { 240156, 240157 },
                      specs = { PRIEST_SHADOW } },
                    { name = "Thalassian Haste", itemId = 244010,
                      qualities = { 244010, 244011 },
                      specs = { PRIEST_SHADOW } },
                },
            },
            ---------------------------------------------------------------------------
            -- Flask
            ---------------------------------------------------------------------------
            {
                category = "Flask",
                items = {
                    { name = "Flask of the Shattered Sun", itemId = 241326,
                      qualities = { 241326, 241327 },
                      specs = { DEATHKNIGHT_BLOOD, DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DEMONHUNTER_HAVOC, DEMONHUNTER_VENGEANCE, DEMONHUNTER_DEVOURER, DRUID_BALANCE, EVOKER_DEVASTATION, HUNTER_MARKSMANSHIP, MAGE_FROST, MONK_BREWMASTER, PALADIN_HOLY, PALADIN_PROTECTION, PRIEST_HOLY, ROGUE_ASSASSINATION, ROGUE_OUTLAW, SHAMAN_ELEMENTAL, SHAMAN_RESTORATION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION, WARRIOR_ARMS, WARRIOR_PROT } },
                    { name = "Flask of the Blood Knights", itemId = 241325,
                      qualities = { 241324, 241325 },
                      specs = { DEATHKNIGHT_BLOOD, DEATHKNIGHT_FROST_DK, DEMONHUNTER_VENGEANCE, DEMONHUNTER_DEVOURER, DRUID_FERAL, DRUID_GUARDIAN, DRUID_RESTORATION, EVOKER_DEVASTATION, EVOKER_PRESERVATION, MONK_MISTWEAVER, MONK_WINDWALKER, PALADIN_HOLY, PRIEST_DISCIPLINE, PRIEST_SHADOW, ROGUE_ASSASSINATION, ROGUE_OUTLAW, ROGUE_SUBTLETY, SHAMAN_ENHANCEMENT, WARLOCK_AFFLICTION, WARRIOR_ARMS, WARRIOR_FURY, WARRIOR_PROT } },
                    { name = "Flask of Thalassian Resistance", itemId = 241320,
                      qualities = { 241320, 241321 },
                      specs = { DEATHKNIGHT_BLOOD, DEMONHUNTER_VENGEANCE, MAGE_ARCANE, MAGE_FIRE, MONK_BREWMASTER, MONK_MISTWEAVER, PRIEST_HOLY, PRIEST_SHADOW, SHAMAN_RESTORATION } },
                    { name = "Flask of the Magisters", itemId = 241322,
                      qualities = { 241322, 241323 },
                      specs = { DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DEMONHUNTER_HAVOC, DEMONHUNTER_DEVOURER, DRUID_BALANCE, DRUID_FERAL, DRUID_RESTORATION, EVOKER_PRESERVATION, EVOKER_AUGMENTATION, HUNTER_BEAST_MASTERY, HUNTER_SURVIVAL, MONK_BREWMASTER, PALADIN_HOLY, PALADIN_RETRIBUTION, PRIEST_SHADOW, ROGUE_SUBTLETY, SHAMAN_ELEMENTAL, SHAMAN_ENHANCEMENT, WARRIOR_FURY } },
                    { name = "Freightrunner's Flask", itemId = 250215,
                      specs = { DEMONHUNTER_DEVOURER } },
                    { name = "Aqirbane Reliquary", itemId = 268265,
                      specs = { DEMONHUNTER_DEVOURER } },
                },
            },
            ---------------------------------------------------------------------------
            -- Potions
            ---------------------------------------------------------------------------
            {
                category = "Potions",
                items = {
                    { name = "Potion of Recklessness", itemId = 241288,
                      qualities = { 241288, 241289 },
                      specs = { DEATHKNIGHT_BLOOD, DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DEMONHUNTER_HAVOC, DEMONHUNTER_VENGEANCE, DEMONHUNTER_DEVOURER, DRUID_FERAL, DRUID_RESTORATION, EVOKER_DEVASTATION, EVOKER_PRESERVATION, EVOKER_AUGMENTATION, HUNTER_BEAST_MASTERY, HUNTER_MARKSMANSHIP, HUNTER_SURVIVAL, MAGE_FROST, MONK_WINDWALKER, PALADIN_RETRIBUTION, PRIEST_DISCIPLINE, PRIEST_HOLY, PRIEST_SHADOW, ROGUE_OUTLAW, ROGUE_SUBTLETY, SHAMAN_ELEMENTAL, SHAMAN_ENHANCEMENT, WARRIOR_ARMS, WARRIOR_FURY, WARRIOR_PROT } },
                    { name = "Light's Potential", itemId = 241308,
                      qualities = { 241308, 241309 },
                      specs = { DEATHKNIGHT_BLOOD, DEATHKNIGHT_FROST_DK, DEMONHUNTER_DEVOURER, DRUID_BALANCE, DRUID_GUARDIAN, EVOKER_AUGMENTATION, HUNTER_BEAST_MASTERY, HUNTER_MARKSMANSHIP, HUNTER_SURVIVAL, MAGE_ARCANE, MAGE_FIRE, MONK_BREWMASTER, MONK_MISTWEAVER, PALADIN_HOLY, PALADIN_PROTECTION, PALADIN_RETRIBUTION, PRIEST_DISCIPLINE, PRIEST_HOLY, PRIEST_SHADOW, ROGUE_ASSASSINATION, ROGUE_SUBTLETY, SHAMAN_ELEMENTAL, SHAMAN_ENHANCEMENT, SHAMAN_RESTORATION, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION, WARRIOR_ARMS, WARRIOR_FURY, WARRIOR_PROT } },
                    { name = "Draught of Rampant Abandon", itemId = 241292,
                      qualities = { 241292, 241293 },
                      specs = { DEATHKNIGHT_BLOOD, DEMONHUNTER_HAVOC, DRUID_BALANCE, DRUID_FERAL, EVOKER_DEVASTATION, EVOKER_AUGMENTATION, MONK_BREWMASTER, ROGUE_SUBTLETY, SHAMAN_ELEMENTAL, SHAMAN_ENHANCEMENT, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION, WARRIOR_PROT } },
                    { name = "Concentrated Silvermoon Health Potion", itemId = 271883,
                      qualities = { 271883, 271884 } },
                    { name = "Algeth'ar Puzzle Box", itemId = 193701,
                      specs = { DEATHKNIGHT_FROST_DK } },
                    { name = "Fleeting Potion of Recklessness", itemId = 245902,
                      qualities = { 245902, 245903 },
                      specs = { DEMONHUNTER_HAVOC, DRUID_FERAL, SHAMAN_ENHANCEMENT } },
                    { name = "Lightfused Mana Potion", itemId = 241301,
                      qualities = { 241300, 241301 },
                      specs = { EVOKER_PRESERVATION, MONK_MISTWEAVER, PALADIN_HOLY, PRIEST_HOLY } },
                    { name = "Potion of Devoured Dreams", itemId = 241294,
                      qualities = { 241294, 241295 },
                      specs = { MONK_MISTWEAVER, PRIEST_DISCIPLINE, PRIEST_HOLY } },
                    { name = "Fleeting Light's Potential", itemId = 245898,
                      qualities = { 245897, 245898 },
                      specs = { SHAMAN_RESTORATION } },
                },
            },
            ---------------------------------------------------------------------------
            -- Food Buff
            ---------------------------------------------------------------------------
            {
                category = "Food Buff",
                items = {
                    { name = "Harandar Celebration", itemId = 255846,
                      specs = { DEATHKNIGHT_BLOOD, DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DRUID_BALANCE, DRUID_GUARDIAN, DRUID_RESTORATION, HUNTER_BEAST_MASTERY, HUNTER_MARKSMANSHIP, HUNTER_SURVIVAL, MAGE_FROST, MONK_BREWMASTER, MONK_MISTWEAVER, MONK_WINDWALKER, PALADIN_PROTECTION, PRIEST_DISCIPLINE, PRIEST_HOLY, PRIEST_SHADOW, ROGUE_SUBTLETY, SHAMAN_ELEMENTAL, SHAMAN_RESTORATION, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION, WARRIOR_ARMS, WARRIOR_FURY, WARRIOR_PROT } },
                    { name = "Blooming Feast", itemId = 242273,
                      specs = { DEATHKNIGHT_BLOOD, MONK_BREWMASTER, PALADIN_PROTECTION, PRIEST_DISCIPLINE, WARRIOR_PROT } },
                    { name = "Royal Roast", itemId = 242275,
                      specs = { DEATHKNIGHT_BLOOD, DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DEMONHUNTER_HAVOC, DEMONHUNTER_VENGEANCE, DRUID_BALANCE, DRUID_FERAL, DRUID_GUARDIAN, EVOKER_DEVASTATION, EVOKER_AUGMENTATION, MAGE_FROST, MONK_BREWMASTER, MONK_MISTWEAVER, MONK_WINDWALKER, PALADIN_RETRIBUTION, PRIEST_DISCIPLINE, PRIEST_HOLY, PRIEST_SHADOW, ROGUE_ASSASSINATION, ROGUE_OUTLAW, ROGUE_SUBTLETY, SHAMAN_ELEMENTAL, SHAMAN_ENHANCEMENT, SHAMAN_RESTORATION, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION, WARRIOR_ARMS, WARRIOR_FURY, WARRIOR_PROT } },
                    { name = "Champion's Bento", itemId = 242274,
                      specs = { DEATHKNIGHT_BLOOD, DEMONHUNTER_DEVOURER, MONK_BREWMASTER, PALADIN_PROTECTION, PRIEST_DISCIPLINE, WARRIOR_PROT } },
                    { name = "Silvermoon Parade", itemId = 255845,
                      specs = { DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DEMONHUNTER_HAVOC, DEMONHUNTER_VENGEANCE, DRUID_BALANCE, DRUID_FERAL, DRUID_GUARDIAN, DRUID_RESTORATION, EVOKER_DEVASTATION, EVOKER_AUGMENTATION, HUNTER_BEAST_MASTERY, HUNTER_MARKSMANSHIP, HUNTER_SURVIVAL, MAGE_ARCANE, MAGE_FIRE, MAGE_FROST, MONK_BREWMASTER, MONK_MISTWEAVER, PRIEST_DISCIPLINE, PRIEST_HOLY, PRIEST_SHADOW, ROGUE_ASSASSINATION, ROGUE_OUTLAW, SHAMAN_ELEMENTAL, SHAMAN_ENHANCEMENT, SHAMAN_RESTORATION } },
                    { name = "Impossibly Royal Roast", itemId = 255847,
                      specs = { DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DRUID_RESTORATION, MAGE_FROST, MONK_BREWMASTER, PRIEST_HOLY, SHAMAN_ELEMENTAL } },
                    { name = "Feast of Knowledge", itemId = 275266,
                      specs = { DEMONHUNTER_DEVOURER } },
                    { name = "Quel'dorei Medley", itemId = 242272,
                      specs = { DRUID_RESTORATION, PRIEST_DISCIPLINE } },
                    { name = "Sun-Seared Lumifin", itemId = 242283,
                      specs = { PRIEST_HOLY } },
                    { name = "Arcano Cutlets", itemId = 242287,
                      specs = { PRIEST_HOLY } },
                    { name = "Warped Wise Wings", itemId = 242285,
                      specs = { PRIEST_SHADOW } },
                    { name = "Fel-Kissed Filet", itemId = 242286,
                      specs = { PRIEST_SHADOW } },
                },
            },
            ---------------------------------------------------------------------------
            -- Augment Rune
            ---------------------------------------------------------------------------
            {
                category = "Augment Rune",
                items = {
                    { name = "Void-Touched Augment Rune", itemId = 259085,
                      specs = { DEATHKNIGHT_BLOOD, DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DEMONHUNTER_HAVOC, DEMONHUNTER_DEVOURER, DRUID_BALANCE, DRUID_FERAL, DRUID_GUARDIAN, DRUID_RESTORATION, EVOKER_DEVASTATION, EVOKER_PRESERVATION, EVOKER_AUGMENTATION, HUNTER_BEAST_MASTERY, HUNTER_MARKSMANSHIP, HUNTER_SURVIVAL, MAGE_ARCANE, MAGE_FIRE, MAGE_FROST, MONK_BREWMASTER, MONK_MISTWEAVER, MONK_WINDWALKER, PALADIN_PROTECTION, PALADIN_RETRIBUTION, PRIEST_DISCIPLINE, PRIEST_HOLY, PRIEST_SHADOW, ROGUE_ASSASSINATION, ROGUE_OUTLAW, ROGUE_SUBTLETY, SHAMAN_ELEMENTAL, SHAMAN_ENHANCEMENT, SHAMAN_RESTORATION, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION, WARRIOR_ARMS, WARRIOR_FURY, WARRIOR_PROT } },
                    { name = "Ethereal Augment Rune", itemId = 243191,
                      specs = { DEATHKNIGHT_BLOOD } },
                },
            },
            ---------------------------------------------------------------------------
            -- Other Consumables
            ---------------------------------------------------------------------------
            {
                category = "Other Consumables",
                items = {
                    { name = "Gateway Control Shard", itemId = 188152,
                      specs = { DEMONHUNTER_HAVOC, DEMONHUNTER_DEVOURER, DRUID_FERAL, PRIEST_HOLY, PRIEST_SHADOW, SHAMAN_ENHANCEMENT } },
                    { name = "Void-Touched Drums", itemId = 244639,
                      specs = { DEMONHUNTER_HAVOC, DEMONHUNTER_DEVOURER, DRUID_FERAL, MONK_BREWMASTER, PRIEST_HOLY, PRIEST_SHADOW } },
                    { name = "Emergency Soul Link", itemId = 269586,
                      qualities = { 248486, 269586 },
                      specs = { DEMONHUNTER_HAVOC, DEMONHUNTER_DEVOURER, MONK_BREWMASTER, PRIEST_HOLY, PRIEST_SHADOW, SHAMAN_ENHANCEMENT } },
                    { name = "Void-Shrouded Tincture", itemId = 241303,
                      qualities = { 241302, 241303 },
                      specs = { DEMONHUNTER_HAVOC, DEMONHUNTER_DEVOURER, DRUID_FERAL, PRIEST_HOLY, PRIEST_SHADOW, SHAMAN_ENHANCEMENT } },
                    { name = "Tempered Potion", itemId = 212265,
                      qualities = { 212264, 212265 },
                      specs = { PRIEST_HOLY } },
                },
            },
            ---------------------------------------------------------------------------
            -- Potion
            ---------------------------------------------------------------------------
            {
                category = "Potion",
                items = {
                    { name = "Silvermoon Health Potion", itemId = 241305,
                      qualities = { 241305, 241304 },
                      specs = { EVOKER_AUGMENTATION, MONK_BREWMASTER, MONK_MISTWEAVER, PRIEST_HOLY, PRIEST_SHADOW, ROGUE_ASSASSINATION, ROGUE_OUTLAW } },
                },
            },
            ---------------------------------------------------------------------------
            -- And Vantus Rune
            ---------------------------------------------------------------------------
            {
                category = "And Vantus Rune",
                items = {
                    { name = "Vantus Rune: Radiant", itemId = 245879,
                      qualities = { 245879, 245880 },
                      specs = { SHAMAN_ELEMENTAL } },
                },
            },
        },
        EnchantData = {
            ---------------------------------------------------------------------------
            -- Recommended Gems
            ---------------------------------------------------------------------------
            {
                category = "Recommended Gems",
                items = {
                    { name = "Indecipherable Eversong Diamond", itemId = 240983,
                      qualities = { 240982, 240983 },
                      specs = { DEATHKNIGHT_BLOOD, DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DEMONHUNTER_HAVOC, DEMONHUNTER_VENGEANCE, DEMONHUNTER_DEVOURER, DRUID_BALANCE, DRUID_FERAL, DRUID_GUARDIAN, DRUID_RESTORATION, EVOKER_PRESERVATION, EVOKER_AUGMENTATION, HUNTER_BEAST_MASTERY, HUNTER_MARKSMANSHIP, HUNTER_SURVIVAL, MAGE_ARCANE, MAGE_FIRE, MAGE_FROST, MONK_BREWMASTER, MONK_MISTWEAVER, MONK_WINDWALKER, PALADIN_HOLY, PALADIN_PROTECTION, PALADIN_RETRIBUTION, PRIEST_DISCIPLINE, PRIEST_HOLY, PRIEST_SHADOW, ROGUE_SUBTLETY, SHAMAN_ELEMENTAL, SHAMAN_ENHANCEMENT, SHAMAN_RESTORATION, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION, WARRIOR_ARMS, WARRIOR_FURY, WARRIOR_PROT } },
                    { name = "Powerful Eversong Diamond", itemId = 240967,
                      qualities = { 240966, 240967 },
                      specs = { DEATHKNIGHT_BLOOD, DEMONHUNTER_HAVOC, DRUID_FERAL, DRUID_RESTORATION, EVOKER_DEVASTATION, HUNTER_MARKSMANSHIP, MAGE_ARCANE, MAGE_FIRE, MONK_BREWMASTER, ROGUE_ASSASSINATION, ROGUE_OUTLAW, SHAMAN_ENHANCEMENT, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION, WARRIOR_ARMS, WARRIOR_FURY } },
                    { name = "Flawless Masterful Garnet", itemId = 240908,
                      qualities = { 240907, 240908 },
                      specs = { DEATHKNIGHT_BLOOD, DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DEMONHUNTER_HAVOC, DRUID_BALANCE, DRUID_FERAL, EVOKER_PRESERVATION, HUNTER_MARKSMANSHIP, MAGE_FROST, MONK_WINDWALKER, PALADIN_HOLY, PRIEST_SHADOW, ROGUE_SUBTLETY, SHAMAN_ELEMENTAL, SHAMAN_ENHANCEMENT } },
                    { name = "Flawless Quick Garnet", itemId = 240906,
                      qualities = { 240905, 240906 },
                      specs = { DEATHKNIGHT_BLOOD, DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, EVOKER_DEVASTATION, MAGE_ARCANE, MAGE_FIRE, MONK_WINDWALKER, PRIEST_SHADOW, ROGUE_ASSASSINATION, ROGUE_OUTLAW, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION, WARRIOR_ARMS, WARRIOR_FURY } },
                    { name = "Flawless Deadly Amethyst", itemId = 240898,
                      qualities = { 240897, 240898 },
                      specs = { DEMONHUNTER_HAVOC, DEMONHUNTER_DEVOURER, DRUID_BALANCE, EVOKER_DEVASTATION, EVOKER_AUGMENTATION, HUNTER_BEAST_MASTERY, HUNTER_MARKSMANSHIP, HUNTER_SURVIVAL, MONK_WINDWALKER, PRIEST_HOLY, ROGUE_ASSASSINATION, ROGUE_OUTLAW, ROGUE_SUBTLETY, SHAMAN_ELEMENTAL, SHAMAN_RESTORATION, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION } },
                    { name = "Flawless Deadly Peridot", itemId = 240890,
                      qualities = { 240889, 240890 },
                      specs = { DEMONHUNTER_HAVOC, DEMONHUNTER_VENGEANCE, DRUID_BALANCE, EVOKER_DEVASTATION, HUNTER_MARKSMANSHIP, MONK_MISTWEAVER, MONK_WINDWALKER, PRIEST_HOLY, ROGUE_ASSASSINATION, ROGUE_OUTLAW, ROGUE_SUBTLETY, SHAMAN_RESTORATION, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION, WARRIOR_ARMS, WARRIOR_PROT } },
                    { name = "Flawless Deadly Lapis", itemId = 240914,
                      qualities = { 240913, 240914 },
                      specs = { DEMONHUNTER_HAVOC, DRUID_BALANCE, EVOKER_DEVASTATION, HUNTER_MARKSMANSHIP, MONK_BREWMASTER, PRIEST_HOLY, ROGUE_ASSASSINATION, ROGUE_OUTLAW, SHAMAN_RESTORATION, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION } },
                    { name = "Flawless Versatile Garnet", itemId = 240910,
                      qualities = { 240909, 240910 },
                      specs = { DEMONHUNTER_VENGEANCE, MONK_BREWMASTER, PRIEST_HOLY, SHAMAN_RESTORATION } },
                    { name = "Flawless Quick Amethyst", itemId = 240900,
                      qualities = { 240899, 240900 },
                      specs = { DRUID_FERAL, EVOKER_PRESERVATION, EVOKER_AUGMENTATION, MAGE_ARCANE, MAGE_FIRE, MONK_WINDWALKER, PALADIN_HOLY, PRIEST_SHADOW, SHAMAN_ENHANCEMENT, WARLOCK_DESTRUCTION } },
                    { name = "Flawless Masterful Peridot", itemId = 240892,
                      qualities = { 240891, 240892 },
                      specs = { DRUID_FERAL, DRUID_RESTORATION, EVOKER_PRESERVATION, MAGE_ARCANE, MONK_WINDWALKER, PALADIN_HOLY, PALADIN_PROTECTION, PALADIN_RETRIBUTION, PRIEST_DISCIPLINE, PRIEST_SHADOW, ROGUE_SUBTLETY, SHAMAN_ENHANCEMENT, WARRIOR_FURY } },
                    { name = "Flawless Masterful Lapis", itemId = 240917,
                      qualities = { 240917, 240918 },
                      specs = { DRUID_FERAL, EVOKER_PRESERVATION, PALADIN_HOLY, PRIEST_SHADOW, SHAMAN_ENHANCEMENT } },
                    { name = "Flawless Versatile Peridot", itemId = 240893,
                      qualities = { 240893, 240894 },
                      specs = { DRUID_GUARDIAN, MAGE_FIRE, WARRIOR_PROT } },
                    { name = "Stoic Eversong Diamond", itemId = 240970,
                      qualities = { 240970, 240971 },
                      specs = { DRUID_RESTORATION } },
                    { name = "Telluric Eversong Diamond", itemId = 240968,
                      qualities = { 240968, 240969 },
                      specs = { DRUID_RESTORATION, EVOKER_PRESERVATION, PALADIN_HOLY, SHAMAN_RESTORATION } },
                    { name = "Flawless Quick Lapis", itemId = 240916,
                      qualities = { 240915, 240916 },
                      specs = { MAGE_ARCANE, MAGE_FIRE, MONK_MISTWEAVER, PRIEST_SHADOW } },
                    { name = "Miasmic Jewelbinder", itemId = 275707,
                      specs = { MONK_BREWMASTER, PRIEST_DISCIPLINE, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION } },
                    { name = "Gaze of the Coiled Watcher", itemId = 271875,
                      specs = { ROGUE_ASSASSINATION } },
                    { name = "Alluring Bubbleband", itemId = 268266,
                      specs = { ROGUE_ASSASSINATION } },
                },
            },
        },
    },
}

ConsumableHelper.UtilityData = {
    ---------------------------------------------------------------------------
    -- Vantus Rune
    ---------------------------------------------------------------------------
    {
        category = "Vantus Rune",
        items = {
            { name = "Vantus Rune: Radiant", itemId = 245879,
              qualities = { 245879, 245880 } },
        },
    },
    ---------------------------------------------------------------------------
    -- Potions
    ---------------------------------------------------------------------------
    {
        category = "Potions",
        items = {
            { name = "Silvermoon Health Potion", itemId = 241304,
              qualities = { 241305, 241304 } },
            { name = "Lightfused Mana Potion", itemId = 241300,
              qualities = { 241300, 241301 } },
            { name = "Refreshing Serum", itemId = 241306,
              qualities = { 241306, 241307 } },
            { name = "Potion of Invisibility", itemId = 241302,
              qualities = { 241302, 241303 } },
            { name = "Slowfall Potion", itemId = 241338,
              qualities = { 241338, 241339 } },
        },
    },
    ---------------------------------------------------------------------------
    -- Useful Consumables
    ---------------------------------------------------------------------------
    {
        category = "Useful Consumables",
        items = {
            { name = "Auto Repair Hammer", itemId = 132514 },
            { name = "Void-Touched Drums", itemId = 244639 },
            { name = "Emergency Soul Link", itemId = 248486,
              qualities = { 248486, 269586 } },
        },
    },
}
