local _, ConsumableHelper = ...

-------------------------------------------------------------------------------
-- Auto-generated by consumablehelper_scraper — do not edit manually
-- Generated: 2026-04-10T17:41:34.732Z
-------------------------------------------------------------------------------

-- Spec ID constants
local MAGE_ARCANE = 62
local MAGE_FIRE = 63
local MAGE_FROST = 64
local PALADIN_HOLY = 65
local PALADIN_PROTECTION = 66
local PALADIN_RETRIBUTION = 70
local WARRIOR_ARMS = 71
local WARRIOR_FURY = 72
local WARRIOR_PROT = 73
local DRUID_BALANCE = 102
local DRUID_FERAL = 103
local DRUID_GUARDIAN = 104
local DRUID_RESTORATION = 105
local DEATHKNIGHT_BLOOD = 250
local DEATHKNIGHT_FROST_DK = 251
local DEATHKNIGHT_UNHOLY = 252
local HUNTER_BEAST_MASTERY = 253
local HUNTER_MARKSMANSHIP = 254
local HUNTER_SURVIVAL = 255
local PRIEST_DISCIPLINE = 256
local PRIEST_HOLY = 257
local PRIEST_SHADOW = 258
local ROGUE_ASSASSINATION = 259
local ROGUE_OUTLAW = 260
local ROGUE_SUBTLETY = 261
local SHAMAN_ELEMENTAL = 262
local SHAMAN_ENHANCEMENT = 263
local SHAMAN_RESTORATION = 264
local WARLOCK_AFFLICTION = 265
local WARLOCK_DEMONOLOGY = 266
local WARLOCK_DESTRUCTION = 267
local MONK_BREWMASTER = 268
local MONK_WINDWALKER = 269
local MONK_MISTWEAVER = 270
local DEMONHUNTER_HAVOC = 577
local DEMONHUNTER_VENGEANCE = 581
local EVOKER_DEVASTATION = 1467
local EVOKER_PRESERVATION = 1468
local EVOKER_AUGMENTATION = 1473

ConsumableHelper.ConsumableData = {
    ---------------------------------------------------------------------------
    -- Flask
    ---------------------------------------------------------------------------
    {
        category = "Flask",
        items = {
            { name = "Flask of the Shattered Sun", itemId = 241326,
              qualities = { 241326, 241327 },
              specs = { DEATHKNIGHT_BLOOD, DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DEMONHUNTER_HAVOC, DEMONHUNTER_VENGEANCE, DRUID_BALANCE, EVOKER_DEVASTATION, EVOKER_AUGMENTATION, HUNTER_MARKSMANSHIP, MAGE_FROST, MONK_BREWMASTER, PALADIN_HOLY, PALADIN_PROTECTION, PRIEST_HOLY, ROGUE_ASSASSINATION, ROGUE_OUTLAW, SHAMAN_RESTORATION, WARRIOR_ARMS, WARRIOR_PROT } },
            { name = "Flask of the Blood Knights", itemId = 241325,
              qualities = { 241324, 241325 },
              specs = { DEATHKNIGHT_BLOOD, DEMONHUNTER_VENGEANCE, DRUID_GUARDIAN, DRUID_RESTORATION, EVOKER_DEVASTATION, EVOKER_PRESERVATION, MONK_MISTWEAVER, MONK_WINDWALKER, PALADIN_HOLY, PRIEST_DISCIPLINE, PRIEST_SHADOW, ROGUE_OUTLAW, ROGUE_SUBTLETY, SHAMAN_ENHANCEMENT, WARRIOR_ARMS, WARRIOR_FURY, WARRIOR_PROT } },
            { name = "Flask of Thalassian Resistance", itemId = 241320,
              qualities = { 241320, 241321 },
              specs = { DEATHKNIGHT_BLOOD, DEMONHUNTER_VENGEANCE, MAGE_ARCANE, MAGE_FIRE, MONK_MISTWEAVER, PRIEST_HOLY, PRIEST_SHADOW, SHAMAN_RESTORATION } },
        },
    },
    ---------------------------------------------------------------------------
    -- Weapon Augments, and Potions
    ---------------------------------------------------------------------------
    {
        category = "Weapon Augments, and Potions",
        items = {
            { name = "Thalassian Phoenix Oil", itemId = 243733,
              qualities = { 243733, 243734 },
              specs = { DEATHKNIGHT_BLOOD, DEMONHUNTER_HAVOC, DEMONHUNTER_VENGEANCE, DRUID_BALANCE, DRUID_FERAL, DRUID_RESTORATION, EVOKER_DEVASTATION, EVOKER_PRESERVATION, EVOKER_AUGMENTATION, MAGE_FROST, MONK_BREWMASTER, MONK_MISTWEAVER, MONK_WINDWALKER, PALADIN_HOLY, PALADIN_PROTECTION, PALADIN_RETRIBUTION, PRIEST_DISCIPLINE, PRIEST_HOLY, PRIEST_SHADOW, ROGUE_ASSASSINATION, ROGUE_OUTLAW, SHAMAN_ELEMENTAL, SHAMAN_RESTORATION, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION, WARRIOR_ARMS, WARRIOR_FURY, WARRIOR_PROT } },
            { name = "Smuggler's Enchanted Edge", itemId = 243738,
              qualities = { 243737, 243738 },
              specs = { DEATHKNIGHT_BLOOD } },
            { name = "Potion of Recklessness", itemId = 241288,
              qualities = { 241288, 241289 },
              specs = { DEATHKNIGHT_BLOOD, DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DEMONHUNTER_HAVOC, DEMONHUNTER_VENGEANCE, DRUID_RESTORATION, EVOKER_DEVASTATION, EVOKER_PRESERVATION, EVOKER_AUGMENTATION, MAGE_FROST, MONK_WINDWALKER, PALADIN_HOLY, PRIEST_DISCIPLINE, PRIEST_HOLY, ROGUE_ASSASSINATION, ROGUE_OUTLAW, SHAMAN_ELEMENTAL, WARRIOR_ARMS, WARRIOR_FURY, WARRIOR_PROT } },
            { name = "Light's Potential", itemId = 241308,
              qualities = { 241308, 241309 },
              specs = { DEATHKNIGHT_BLOOD, DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DEMONHUNTER_HAVOC, DRUID_BALANCE, DRUID_FERAL, EVOKER_AUGMENTATION, HUNTER_BEAST_MASTERY, HUNTER_MARKSMANSHIP, HUNTER_SURVIVAL, MAGE_ARCANE, MAGE_FIRE, MONK_BREWMASTER, MONK_MISTWEAVER, PALADIN_PROTECTION, PALADIN_RETRIBUTION, PRIEST_HOLY, PRIEST_SHADOW, ROGUE_SUBTLETY, SHAMAN_ELEMENTAL, SHAMAN_ENHANCEMENT, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION, WARRIOR_ARMS, WARRIOR_FURY, WARRIOR_PROT } },
            { name = "Potion of Zealotry", itemId = 241296,
              qualities = { 241296, 241297 },
              specs = { DEATHKNIGHT_BLOOD } },
            { name = "Draught of Rampant Abandon", itemId = 241292,
              qualities = { 241292, 241293 },
              specs = { DEATHKNIGHT_BLOOD, DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DEMONHUNTER_HAVOC, DRUID_BALANCE, DRUID_FERAL, DRUID_GUARDIAN, HUNTER_BEAST_MASTERY, HUNTER_MARKSMANSHIP, HUNTER_SURVIVAL, MONK_BREWMASTER, PALADIN_RETRIBUTION, PRIEST_SHADOW, ROGUE_SUBTLETY, SHAMAN_ELEMENTAL, SHAMAN_ENHANCEMENT, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION, WARRIOR_PROT } },
            { name = "Silvermoon Health Potion", itemId = 241305,
              qualities = { 241305, 241304 },
              specs = { DEATHKNIGHT_BLOOD, DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DEMONHUNTER_HAVOC, DEMONHUNTER_VENGEANCE, DRUID_BALANCE, DRUID_FERAL, DRUID_GUARDIAN, DRUID_RESTORATION, EVOKER_PRESERVATION, HUNTER_BEAST_MASTERY, HUNTER_MARKSMANSHIP, HUNTER_SURVIVAL, MAGE_ARCANE, MAGE_FIRE, MAGE_FROST, MONK_BREWMASTER, MONK_WINDWALKER, PALADIN_HOLY, PALADIN_PROTECTION, PALADIN_RETRIBUTION, PRIEST_DISCIPLINE, PRIEST_HOLY, PRIEST_SHADOW, ROGUE_ASSASSINATION, ROGUE_OUTLAW, ROGUE_SUBTLETY, SHAMAN_ELEMENTAL, SHAMAN_ENHANCEMENT, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION, WARRIOR_ARMS, WARRIOR_FURY, WARRIOR_PROT } },
        },
    },
    ---------------------------------------------------------------------------
    -- Food
    ---------------------------------------------------------------------------
    {
        category = "Food",
        items = {
            { name = "Harandar Celebration", itemId = 255846,
              specs = { DEATHKNIGHT_BLOOD, DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DRUID_BALANCE, DRUID_GUARDIAN, DRUID_RESTORATION, HUNTER_BEAST_MASTERY, HUNTER_MARKSMANSHIP, HUNTER_SURVIVAL, MAGE_FROST, MONK_BREWMASTER, MONK_MISTWEAVER, MONK_WINDWALKER, PALADIN_PROTECTION, PRIEST_HOLY, PRIEST_SHADOW, ROGUE_SUBTLETY, SHAMAN_ELEMENTAL, SHAMAN_RESTORATION, WARRIOR_FURY, WARRIOR_PROT } },
            { name = "Blooming Feast", itemId = 242273,
              specs = { DEATHKNIGHT_BLOOD, MAGE_ARCANE, MAGE_FIRE, MONK_BREWMASTER, PALADIN_PROTECTION, SHAMAN_ELEMENTAL, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION, WARRIOR_ARMS, WARRIOR_PROT } },
            { name = "Royal Roast", itemId = 242275,
              specs = { DEATHKNIGHT_BLOOD, DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DEMONHUNTER_HAVOC, DEMONHUNTER_VENGEANCE, DRUID_BALANCE, DRUID_FERAL, EVOKER_DEVASTATION, EVOKER_AUGMENTATION, MAGE_FROST, MONK_BREWMASTER, MONK_MISTWEAVER, PALADIN_PROTECTION, PALADIN_RETRIBUTION, PRIEST_DISCIPLINE, PRIEST_HOLY, PRIEST_SHADOW, ROGUE_ASSASSINATION, ROGUE_OUTLAW, ROGUE_SUBTLETY, SHAMAN_ELEMENTAL, SHAMAN_ENHANCEMENT, SHAMAN_RESTORATION, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION, WARRIOR_FURY, WARRIOR_PROT } },
            { name = "Champion's Bento", itemId = 242274,
              specs = { DEATHKNIGHT_BLOOD, MAGE_ARCANE, MAGE_FIRE, MONK_BREWMASTER, PALADIN_PROTECTION, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION, WARRIOR_ARMS, WARRIOR_PROT } },
            { name = "Silvermoon Parade", itemId = 255845,
              specs = { DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DEMONHUNTER_HAVOC, DEMONHUNTER_VENGEANCE, DRUID_BALANCE, DRUID_FERAL, DRUID_GUARDIAN, DRUID_RESTORATION, EVOKER_DEVASTATION, EVOKER_AUGMENTATION, HUNTER_BEAST_MASTERY, HUNTER_MARKSMANSHIP, HUNTER_SURVIVAL, MAGE_FROST, MONK_BREWMASTER, MONK_MISTWEAVER, PRIEST_HOLY, PRIEST_SHADOW, ROGUE_ASSASSINATION, ROGUE_OUTLAW, SHAMAN_ELEMENTAL, SHAMAN_ENHANCEMENT, SHAMAN_RESTORATION, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION } },
            { name = "Impossibly Royal Roast", itemId = 255847,
              specs = { DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DRUID_RESTORATION, MAGE_FROST, MONK_BREWMASTER, PRIEST_HOLY, SHAMAN_ELEMENTAL } },
            { name = "Sun-Seared Lumifin", itemId = 242283,
              specs = { PRIEST_HOLY } },
            { name = "Arcano Cutlets", itemId = 242287,
              specs = { PRIEST_HOLY } },
            { name = "Warped Wise Wings", itemId = 242285,
              specs = { PRIEST_SHADOW } },
            { name = "Fel-Kissed Filet", itemId = 242286,
              specs = { PRIEST_SHADOW } },
            { name = "Sanguithorn Tea", itemId = 242299,
              classes = { "WARLOCK" } },
            { name = "Azeroot Tea", itemId = 242301,
              classes = { "WARLOCK" } },
            { name = "Argentleaf Tea", itemId = 242298,
              classes = { "WARLOCK" } },
        },
    },
    ---------------------------------------------------------------------------
    -- Augment Runes
    ---------------------------------------------------------------------------
    {
        category = "Augment Runes",
        items = {
            { name = "Void-Touched Augment Rune", itemId = 259085,
              specs = { DEATHKNIGHT_BLOOD, DEMONHUNTER_HAVOC, DRUID_BALANCE, DRUID_FERAL, DRUID_RESTORATION, EVOKER_DEVASTATION, EVOKER_AUGMENTATION, HUNTER_BEAST_MASTERY, HUNTER_MARKSMANSHIP, HUNTER_SURVIVAL, MAGE_ARCANE, MAGE_FIRE, MAGE_FROST, MONK_BREWMASTER, MONK_WINDWALKER, PALADIN_PROTECTION, PALADIN_RETRIBUTION, PRIEST_DISCIPLINE, PRIEST_HOLY, PRIEST_SHADOW, ROGUE_ASSASSINATION, ROGUE_OUTLAW, ROGUE_SUBTLETY, SHAMAN_ELEMENTAL, SHAMAN_ENHANCEMENT, SHAMAN_RESTORATION, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION, WARRIOR_ARMS, WARRIOR_FURY, WARRIOR_PROT } },
        },
    },
    ---------------------------------------------------------------------------
    -- Flasks
    ---------------------------------------------------------------------------
    {
        category = "Flasks",
        items = {
            { name = "Flask of the Magisters", itemId = 241322,
              qualities = { 241322, 241323 },
              specs = { DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DEMONHUNTER_HAVOC, DRUID_BALANCE, DRUID_FERAL, DRUID_RESTORATION, EVOKER_PRESERVATION, HUNTER_BEAST_MASTERY, HUNTER_SURVIVAL, MONK_BREWMASTER, PALADIN_HOLY, PALADIN_RETRIBUTION, PRIEST_SHADOW, ROGUE_SUBTLETY, SHAMAN_ELEMENTAL, SHAMAN_ENHANCEMENT, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION, WARRIOR_FURY } },
        },
    },
    ---------------------------------------------------------------------------
    -- Potions
    ---------------------------------------------------------------------------
    {
        category = "Potions",
        items = {
            { name = "Fleeting Light's Potential", itemId = 245898,
              qualities = { 245897, 245898 },
              specs = { DEMONHUNTER_HAVOC, DRUID_FERAL, SHAMAN_ENHANCEMENT } },
            { name = "Lightfused Mana Potion", itemId = 241301,
              qualities = { 241300, 241301 },
              specs = { EVOKER_PRESERVATION, MONK_MISTWEAVER, PALADIN_HOLY, PRIEST_DISCIPLINE, PRIEST_HOLY } },
            { name = "Oil of Dawn", itemId = 243735,
              qualities = { 243735, 243736 },
              specs = { EVOKER_PRESERVATION, PALADIN_HOLY } },
        },
    },
    ---------------------------------------------------------------------------
    -- Other Consumables
    ---------------------------------------------------------------------------
    {
        category = "Other Consumables",
        items = {
            { name = "Gateway Control Shard", itemId = 188152,
              specs = { DEMONHUNTER_HAVOC, DRUID_FERAL, PRIEST_HOLY, PRIEST_SHADOW, SHAMAN_ENHANCEMENT } },
            { name = "Void-Touched Drums", itemId = 244639,
              specs = { DEMONHUNTER_HAVOC, DRUID_FERAL, MONK_BREWMASTER, PRIEST_HOLY, PRIEST_SHADOW } },
            { name = "Emergency Soul Link", itemId = 269586,
              qualities = { 248486, 269586 },
              specs = { DEMONHUNTER_HAVOC, MONK_BREWMASTER, PRIEST_HOLY, PRIEST_SHADOW, SHAMAN_ENHANCEMENT } },
            { name = "Void-Shrouded Tincture", itemId = 241303,
              qualities = { 241302, 241303 },
              specs = { DEMONHUNTER_HAVOC, DRUID_FERAL, PRIEST_HOLY, PRIEST_SHADOW, SHAMAN_ENHANCEMENT } },
            { name = "Tempered Potion", itemId = 212265,
              qualities = { 212264, 212265 },
              specs = { PRIEST_HOLY } },
        },
    },
    ---------------------------------------------------------------------------
    -- Thalassian Diamond
    ---------------------------------------------------------------------------
    {
        category = "Thalassian Diamond",
        items = {
            { name = "Indecipherable Eversong Diamond", itemId = 240983,
              qualities = { 240982, 240983 },
              specs = { DEMONHUNTER_VENGEANCE, EVOKER_AUGMENTATION, MONK_MISTWEAVER, ROGUE_SUBTLETY } },
        },
    },
    ---------------------------------------------------------------------------
    -- Weapon Oil/Stone
    ---------------------------------------------------------------------------
    {
        category = "Weapon Oil/Stone",
        items = {
            { name = "Refulgent Whetstone", itemId = 237371,
              qualities = { 237370, 237371 },
              specs = { DEMONHUNTER_VENGEANCE } },
        },
    },
    ---------------------------------------------------------------------------
    -- Consumables
    ---------------------------------------------------------------------------
    {
        category = "Consumables",
        items = {
            { name = "Quel'dorei Medley", itemId = 242272,
              specs = { DRUID_RESTORATION, MAGE_ARCANE, MAGE_FIRE, SHAMAN_ELEMENTAL } },
        },
    },
    ---------------------------------------------------------------------------
    -- Gems
    ---------------------------------------------------------------------------
    {
        category = "Gems",
        items = {
            { name = "Flawless Deadly Peridot", itemId = 240890,
              qualities = { 240889, 240890 },
              specs = { EVOKER_AUGMENTATION, MONK_MISTWEAVER, ROGUE_SUBTLETY } },
        },
    },
    ---------------------------------------------------------------------------
    -- Enchants
    ---------------------------------------------------------------------------
    {
        category = "Enchants",
        items = {
            { name = "Enchant Weapon - Jan'alai's Precision", itemId = 243970,
              qualities = { 243970, 243971 },
              specs = { EVOKER_AUGMENTATION, ROGUE_ASSASSINATION, ROGUE_OUTLAW } },
            { name = "Enchant Weapon - Acuity of the Ren'dorei", itemId = 244029,
              qualities = { 244028, 244029 },
              specs = { EVOKER_AUGMENTATION } },
            { name = "Enchant Helm - Empowered Blessing of Speed", itemId = 243981,
              qualities = { 243980, 243981 },
              specs = { EVOKER_AUGMENTATION } },
            { name = "Enchant Chest - Mark of the Worldsoul", itemId = 243977,
              qualities = { 243976, 243977 },
              specs = { EVOKER_AUGMENTATION, ROGUE_ASSASSINATION, ROGUE_OUTLAW } },
            { name = "Enchant Shoulders - Akil'zon's Swiftness", itemId = 243962,
              qualities = { 243962, 243963 },
              specs = { EVOKER_AUGMENTATION } },
            { name = "Sunfire Silk Spellthread", itemId = 240133,
              specs = { EVOKER_AUGMENTATION } },
            { name = "Enchant Ring - Nature's Fury", itemId = 243986,
              qualities = { 243986, 243987 },
              specs = { EVOKER_AUGMENTATION, ROGUE_ASSASSINATION, ROGUE_OUTLAW } },
            { name = "Enchant Boots - Farstrider's Hunt", itemId = 244008,
              qualities = { 244008, 244009 },
              specs = { EVOKER_AUGMENTATION } },
        },
    },
    ---------------------------------------------------------------------------
    -- Mythic+
    ---------------------------------------------------------------------------
    {
        category = "Mythic+",
        items = {
            { name = "Flawless Quick Lapis", itemId = 240916,
              qualities = { 240915, 240916 },
              specs = { MONK_MISTWEAVER } },
        },
    },
    ---------------------------------------------------------------------------
    -- Potions and Weapon Oils
    ---------------------------------------------------------------------------
    {
        category = "Potions and Weapon Oils",
        items = {
            { name = "Potion of Devoured Dreams", itemId = 241294,
              qualities = { 241294, 241295 },
              specs = { MONK_MISTWEAVER, PRIEST_DISCIPLINE, PRIEST_HOLY } },
        },
    },
    ---------------------------------------------------------------------------
    -- Enchants and Weapon Oil
    ---------------------------------------------------------------------------
    {
        category = "Enchants and Weapon Oil",
        items = {
            { name = "Enchant Weapon - Berserker's Rage", itemId = 243973,
              qualities = { 243972, 243973 },
              specs = { ROGUE_ASSASSINATION } },
            { name = "Enchant Helm - Empowered Hex of Leeching", itemId = 243950,
              qualities = { 243950, 243951 },
              specs = { ROGUE_ASSASSINATION, ROGUE_OUTLAW } },
            { name = "Enchant Shoulders - Silvermoon's Mending", itemId = 244021,
              qualities = { 244020, 244021 },
              specs = { ROGUE_ASSASSINATION, ROGUE_OUTLAW } },
            { name = "Forest Hunter's Armor Kit", itemId = 244640,
              qualities = { 244640, 244641 },
              specs = { ROGUE_ASSASSINATION, ROGUE_OUTLAW } },
            { name = "Enchant Boots - Shaladrassil's Roots", itemId = 243983,
              qualities = { 243982, 243983 },
              specs = { ROGUE_ASSASSINATION, ROGUE_OUTLAW } },
            { name = "Enchant Ring - Silvermoon's Alacrity", itemId = 244014,
              qualities = { 244014, 244015 },
              specs = { ROGUE_ASSASSINATION, ROGUE_OUTLAW } },
            { name = "Enchant Ring - Eyes of the Eagle", itemId = 243956,
              qualities = { 243956, 243957 },
              specs = { ROGUE_OUTLAW } },
        },
    },
    ---------------------------------------------------------------------------
    -- Enchants, Gems and Consumables
    ---------------------------------------------------------------------------
    {
        category = "Enchants, Gems and Consumables",
        items = {
            { name = "Flawless Masterful Peridot", itemId = 240892,
              qualities = { 240891, 240892 },
              specs = { ROGUE_SUBTLETY } },
            { name = "Flawless Masterful Garnet", itemId = 240908,
              qualities = { 240907, 240908 },
              specs = { ROGUE_SUBTLETY } },
            { name = "Flawless Deadly Amethyst", itemId = 240898,
              qualities = { 240897, 240898 },
              specs = { ROGUE_SUBTLETY } },
        },
    },
    ---------------------------------------------------------------------------
    -- And Vantus Rune
    ---------------------------------------------------------------------------
    {
        category = "And Vantus Rune",
        items = {
            { name = "Vantus Rune: Radiant", itemId = 245879,
              qualities = { 245879, 245880 },
              specs = { SHAMAN_ELEMENTAL } },
        },
    },
}

ConsumableHelper.EnchantData = {
    ---------------------------------------------------------------------------
    -- Gems
    ---------------------------------------------------------------------------
    {
        category = "Gems",
        items = {
            { name = "Indecipherable Eversong Diamond", itemId = 240983,
              qualities = { 240982, 240983 },
              specs = { DEATHKNIGHT_BLOOD, DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DEMONHUNTER_HAVOC, DRUID_BALANCE, DRUID_FERAL, DRUID_GUARDIAN, DRUID_RESTORATION, EVOKER_PRESERVATION, HUNTER_BEAST_MASTERY, HUNTER_MARKSMANSHIP, HUNTER_SURVIVAL, MAGE_ARCANE, MAGE_FIRE, MAGE_FROST, MONK_BREWMASTER, MONK_WINDWALKER, PALADIN_HOLY, PALADIN_PROTECTION, PALADIN_RETRIBUTION, PRIEST_DISCIPLINE, PRIEST_HOLY, PRIEST_SHADOW, ROGUE_OUTLAW, SHAMAN_ENHANCEMENT, SHAMAN_RESTORATION, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION, WARRIOR_ARMS, WARRIOR_FURY, WARRIOR_PROT } },
            { name = "Powerful Eversong Diamond", itemId = 240967,
              qualities = { 240966, 240967 },
              specs = { DEATHKNIGHT_BLOOD, DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DRUID_RESTORATION, EVOKER_DEVASTATION, HUNTER_MARKSMANSHIP, MONK_BREWMASTER, ROGUE_ASSASSINATION, ROGUE_OUTLAW, SHAMAN_ELEMENTAL, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION } },
            { name = "Flawless Masterful Garnet", itemId = 240908,
              qualities = { 240907, 240908 },
              specs = { DEATHKNIGHT_BLOOD, DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DEMONHUNTER_HAVOC, EVOKER_PRESERVATION, HUNTER_MARKSMANSHIP, MAGE_FROST, MONK_WINDWALKER, PALADIN_HOLY, PRIEST_SHADOW, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION } },
            { name = "Flawless Quick Garnet", itemId = 240906,
              qualities = { 240905, 240906 },
              specs = { DEATHKNIGHT_BLOOD, DRUID_BALANCE, EVOKER_DEVASTATION, MONK_WINDWALKER, PRIEST_SHADOW, ROGUE_ASSASSINATION, ROGUE_OUTLAW, WARRIOR_ARMS } },
            { name = "Signet of Azerothian Blessings", itemId = 241140,
              specs = { DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY } },
            { name = "Loa Worshiper's Band", itemId = 251513,
              specs = { DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY } },
            { name = "Flawless Masterful Peridot", itemId = 240892,
              qualities = { 240891, 240892 },
              specs = { DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DRUID_FERAL, DRUID_RESTORATION, EVOKER_PRESERVATION, MAGE_FIRE, MONK_WINDWALKER, PALADIN_HOLY, PALADIN_PROTECTION, PRIEST_SHADOW, SHAMAN_ENHANCEMENT, WARRIOR_FURY } },
            { name = "Flawless Deadly Amethyst", itemId = 240898,
              qualities = { 240897, 240898 },
              specs = { DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DEMONHUNTER_HAVOC, EVOKER_DEVASTATION, HUNTER_BEAST_MASTERY, HUNTER_MARKSMANSHIP, HUNTER_SURVIVAL, MONK_WINDWALKER, PALADIN_RETRIBUTION, PRIEST_HOLY, ROGUE_ASSASSINATION, ROGUE_OUTLAW, SHAMAN_ELEMENTAL, SHAMAN_RESTORATION, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION } },
            { name = "Flawless Masterful Lapis", itemId = 240917,
              qualities = { 240917, 240918 },
              specs = { DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, EVOKER_PRESERVATION, PALADIN_HOLY, PRIEST_SHADOW, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION } },
            { name = "Flawless Quick Lapis", itemId = 240916,
              qualities = { 240915, 240916 },
              specs = { DRUID_BALANCE, PRIEST_SHADOW } },
            { name = "Flawless Quick Amethyst", itemId = 240900,
              qualities = { 240899, 240900 },
              specs = { DRUID_BALANCE, DRUID_FERAL, DRUID_RESTORATION, EVOKER_PRESERVATION, MONK_WINDWALKER, PALADIN_HOLY, PRIEST_SHADOW, SHAMAN_ENHANCEMENT, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION, WARRIOR_FURY } },
            { name = "Flawless Versatile Peridot", itemId = 240893,
              qualities = { 240893, 240894 },
              specs = { DRUID_GUARDIAN, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION, WARRIOR_PROT } },
            { name = "Stoic Eversong Diamond", itemId = 240970,
              qualities = { 240970, 240971 },
              specs = { DRUID_RESTORATION } },
            { name = "Telluric Eversong Diamond", itemId = 240968,
              qualities = { 240968, 240969 },
              specs = { DRUID_RESTORATION, EVOKER_PRESERVATION, PALADIN_HOLY, SHAMAN_RESTORATION } },
            { name = "Flawless Deadly Lapis", itemId = 240914,
              qualities = { 240913, 240914 },
              specs = { EVOKER_DEVASTATION, HUNTER_MARKSMANSHIP, MONK_BREWMASTER, PRIEST_HOLY, ROGUE_ASSASSINATION, ROGUE_OUTLAW, SHAMAN_RESTORATION, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION } },
            { name = "Flawless Versatile Amethyst", itemId = 240902,
              qualities = { 240901, 240902 },
              specs = { MAGE_ARCANE } },
        },
    },
    ---------------------------------------------------------------------------
    -- Enchants
    ---------------------------------------------------------------------------
    {
        category = "Enchants",
        items = {
            { name = "Enchant Helm - Empowered Blessing of Speed", itemId = 243981,
              qualities = { 243980, 243981 },
              specs = { DEATHKNIGHT_BLOOD, DRUID_GUARDIAN, EVOKER_DEVASTATION, MAGE_ARCANE, MAGE_FIRE, MONK_BREWMASTER, PALADIN_PROTECTION, PALADIN_RETRIBUTION, PRIEST_SHADOW, SHAMAN_ELEMENTAL, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION } },
            { name = "Enchant Shoulders - Akil'zon's Swiftness", itemId = 243962,
              qualities = { 243962, 243963 },
              specs = { DEATHKNIGHT_BLOOD, DRUID_GUARDIAN, EVOKER_DEVASTATION, MAGE_ARCANE, MAGE_FIRE, MONK_BREWMASTER, PALADIN_PROTECTION, PALADIN_RETRIBUTION, PRIEST_SHADOW, SHAMAN_ELEMENTAL, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION } },
            { name = "Enchant Chest - Mark of the Worldsoul", itemId = 243977,
              qualities = { 243976, 243977 },
              specs = { DEATHKNIGHT_BLOOD, DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DEMONHUNTER_HAVOC, DEMONHUNTER_VENGEANCE, DRUID_BALANCE, DRUID_FERAL, DRUID_GUARDIAN, DRUID_RESTORATION, EVOKER_DEVASTATION, EVOKER_PRESERVATION, HUNTER_BEAST_MASTERY, HUNTER_MARKSMANSHIP, HUNTER_SURVIVAL, MAGE_ARCANE, MAGE_FIRE, MAGE_FROST, MONK_BREWMASTER, MONK_MISTWEAVER, MONK_WINDWALKER, PALADIN_PROTECTION, PALADIN_RETRIBUTION, PRIEST_HOLY, PRIEST_SHADOW, ROGUE_SUBTLETY, SHAMAN_ELEMENTAL, SHAMAN_ENHANCEMENT, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION, WARRIOR_ARMS, WARRIOR_FURY, WARRIOR_PROT } },
            { name = "Blood Knight's Armor Kit", itemId = 244642,
              qualities = { 244642, 244643 },
              specs = { DEATHKNIGHT_BLOOD, DEMONHUNTER_VENGEANCE, DRUID_GUARDIAN, PALADIN_PROTECTION, WARRIOR_ARMS, WARRIOR_FURY, WARRIOR_PROT } },
            { name = "Enchant Boots - Farstrider's Hunt", itemId = 244008,
              qualities = { 244008, 244009 },
              specs = { DEATHKNIGHT_BLOOD, DRUID_GUARDIAN, EVOKER_DEVASTATION, MAGE_ARCANE, MAGE_FIRE, MONK_BREWMASTER, PALADIN_PROTECTION, PALADIN_RETRIBUTION, PRIEST_HOLY, PRIEST_SHADOW, SHAMAN_ELEMENTAL, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION } },
            { name = "Enchant Ring - Silvermoon's Tenacity", itemId = 244016,
              qualities = { 244016, 244017 },
              specs = { DEATHKNIGHT_BLOOD, MONK_BREWMASTER, PALADIN_PROTECTION } },
            { name = "Enchant Ring - Nature's Fury", itemId = 243986,
              qualities = { 243986, 243987 },
              specs = { DEATHKNIGHT_BLOOD, DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DRUID_BALANCE, MONK_WINDWALKER, PRIEST_HOLY, SHAMAN_RESTORATION } },
            { name = "Ethereal Augment Rune", itemId = 243191,
              specs = { DEATHKNIGHT_BLOOD } },
            { name = "Enchant Helm - Empowered Rune of Avoidance", itemId = 244007,
              qualities = { 244006, 244007 },
              specs = { DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DEMONHUNTER_HAVOC, DRUID_BALANCE, DRUID_FERAL, HUNTER_BEAST_MASTERY, MAGE_FROST, MONK_WINDWALKER, ROGUE_SUBTLETY, SHAMAN_ELEMENTAL, SHAMAN_ENHANCEMENT } },
            { name = "Enchant Shoulders - Amirdrassil's Grace", itemId = 243990,
              qualities = { 243990, 243991 },
              specs = { DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DEMONHUNTER_HAVOC, DRUID_BALANCE, DRUID_FERAL, HUNTER_BEAST_MASTERY, MAGE_FROST, MONK_WINDWALKER, ROGUE_SUBTLETY, SHAMAN_ELEMENTAL, SHAMAN_ENHANCEMENT, WARRIOR_ARMS, WARRIOR_FURY } },
            { name = "Forest Hunter's Armor Kit", itemId = 244640,
              qualities = { 244640, 244641 },
              specs = { DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DEMONHUNTER_HAVOC, DEMONHUNTER_VENGEANCE, DRUID_FERAL, DRUID_GUARDIAN, HUNTER_BEAST_MASTERY, HUNTER_MARKSMANSHIP, HUNTER_SURVIVAL, MONK_BREWMASTER, MONK_WINDWALKER, PALADIN_RETRIBUTION, ROGUE_SUBTLETY, SHAMAN_ENHANCEMENT } },
            { name = "Enchant Boots - Lynx's Dexterity", itemId = 243952,
              qualities = { 243952, 243953 },
              specs = { DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DEMONHUNTER_HAVOC, DRUID_BALANCE, DRUID_FERAL, HUNTER_BEAST_MASTERY, MAGE_FROST, MONK_WINDWALKER, PRIEST_SHADOW, ROGUE_SUBTLETY, SHAMAN_ELEMENTAL, SHAMAN_ENHANCEMENT, WARRIOR_ARMS, WARRIOR_FURY } },
            { name = "Enchant Ring - Zul'jin's Mastery", itemId = 243959,
              qualities = { 243958, 243959 },
              specs = { DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DRUID_RESTORATION, EVOKER_PRESERVATION, HUNTER_BEAST_MASTERY, HUNTER_SURVIVAL, PALADIN_HOLY, PRIEST_SHADOW, SHAMAN_ENHANCEMENT, WARRIOR_FURY } },
            { name = "Enchant Ring - Eyes of the Eagle", itemId = 243956,
              qualities = { 243956, 243957 },
              specs = { DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DEMONHUNTER_HAVOC, DRUID_FERAL, HUNTER_MARKSMANSHIP, MAGE_ARCANE, MAGE_FIRE, MAGE_FROST, MONK_BREWMASTER, PALADIN_RETRIBUTION, ROGUE_SUBTLETY, SHAMAN_ELEMENTAL, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION } },
            { name = "Enchant Weapon - Acuity of the Ren'dorei", itemId = 244029,
              qualities = { 244028, 244029 },
              specs = { DEMONHUNTER_HAVOC, DRUID_BALANCE, DRUID_FERAL, DRUID_RESTORATION, EVOKER_DEVASTATION, EVOKER_PRESERVATION, HUNTER_BEAST_MASTERY, HUNTER_MARKSMANSHIP, HUNTER_SURVIVAL, MAGE_ARCANE, MAGE_FIRE, MONK_BREWMASTER, MONK_MISTWEAVER, MONK_WINDWALKER, PALADIN_HOLY, PALADIN_PROTECTION, PALADIN_RETRIBUTION, PRIEST_DISCIPLINE, PRIEST_HOLY, ROGUE_SUBTLETY, SHAMAN_ENHANCEMENT, SHAMAN_RESTORATION, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION, WARRIOR_ARMS, WARRIOR_PROT } },
            { name = "Enchant Weapon - Berserker's Rage", itemId = 243973,
              qualities = { 243972, 243973 },
              specs = { DEMONHUNTER_VENGEANCE, DRUID_GUARDIAN, PRIEST_DISCIPLINE, PRIEST_SHADOW, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION, WARRIOR_FURY, WARRIOR_PROT } },
            { name = "Enchant Weapon - Jan'alai's Precision", itemId = 243970,
              qualities = { 243970, 243971 },
              specs = { DEMONHUNTER_VENGEANCE, MAGE_FROST, PRIEST_HOLY } },
            { name = "Enchant Weapon - Worldsoul Tenacity", itemId = 244000,
              qualities = { 244000, 244001 },
              specs = { DEMONHUNTER_VENGEANCE, MONK_BREWMASTER } },
            { name = "Enchant Helm - Empowered Hex of Leeching", itemId = 243950,
              qualities = { 243950, 243951 },
              specs = { DEMONHUNTER_VENGEANCE, DRUID_BALANCE, DRUID_RESTORATION, EVOKER_PRESERVATION, HUNTER_MARKSMANSHIP, HUNTER_SURVIVAL, MONK_BREWMASTER, MONK_MISTWEAVER, PALADIN_HOLY, PRIEST_DISCIPLINE, PRIEST_HOLY, SHAMAN_RESTORATION, WARRIOR_ARMS, WARRIOR_FURY, WARRIOR_PROT } },
            { name = "Enchant Shoulders - Silvermoon's Mending", itemId = 244021,
              qualities = { 244020, 244021 },
              specs = { DEMONHUNTER_VENGEANCE, DRUID_BALANCE, DRUID_RESTORATION, EVOKER_PRESERVATION, HUNTER_MARKSMANSHIP, HUNTER_SURVIVAL, MONK_BREWMASTER, MONK_MISTWEAVER, PALADIN_HOLY, PRIEST_DISCIPLINE, PRIEST_HOLY, SHAMAN_RESTORATION, WARRIOR_PROT } },
            { name = "Enchant Boots - Shaladrassil's Roots", itemId = 243983,
              qualities = { 243982, 243983 },
              specs = { DEMONHUNTER_VENGEANCE, DRUID_BALANCE, DRUID_RESTORATION, EVOKER_PRESERVATION, HUNTER_MARKSMANSHIP, HUNTER_SURVIVAL, MONK_BREWMASTER, MONK_MISTWEAVER, PALADIN_HOLY, PRIEST_DISCIPLINE, PRIEST_HOLY, SHAMAN_RESTORATION, WARRIOR_PROT } },
            { name = "Enchant Ring - Silvermoon's Alacrity", itemId = 244014,
              qualities = { 244014, 244015 },
              specs = { DEMONHUNTER_VENGEANCE, DRUID_BALANCE, DRUID_GUARDIAN, EVOKER_DEVASTATION, MONK_MISTWEAVER, MONK_WINDWALKER, PALADIN_HOLY, PRIEST_DISCIPLINE, PRIEST_SHADOW, WARRIOR_ARMS, WARRIOR_PROT } },
            { name = "Sunfire Silk Spellthread", itemId = 240133,
              specs = { DRUID_BALANCE, EVOKER_DEVASTATION, MAGE_FIRE, MAGE_FROST, PRIEST_HOLY, PRIEST_SHADOW, SHAMAN_ELEMENTAL, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION } },
            { name = "Enchant Chest - Mark of the Rootwarden", itemId = 243974,
              qualities = { 243974, 243975 },
              specs = { DRUID_GUARDIAN, MONK_BREWMASTER } },
            { name = "Arcanoweave Spellthread", itemId = 240155,
              qualities = { 240154, 240155 },
              specs = { DRUID_RESTORATION, EVOKER_PRESERVATION, MAGE_ARCANE, MONK_MISTWEAVER, PALADIN_HOLY, PRIEST_DISCIPLINE, PRIEST_HOLY, SHAMAN_RESTORATION } },
            { name = "Enchant Weapon - Arcane Mastery", itemId = 244031,
              qualities = { 244030, 244031 },
              specs = { HUNTER_SURVIVAL, PRIEST_SHADOW, SHAMAN_ELEMENTAL, WARRIOR_FURY } },
            { name = "Adamantite Sharpening Stone", itemId = 23529,
              specs = { HUNTER_SURVIVAL } },
            { name = "Adamantite Weightstone", itemId = 28421,
              specs = { HUNTER_SURVIVAL } },
            { name = "Enchant Weapon - Strength of Halazzi", itemId = 243968,
              qualities = { 243968, 243969 },
              specs = { MONK_BREWMASTER } },
            { name = "Enchant Chest - Mark of the Magister", itemId = 244002,
              qualities = { 244002, 244003 },
              specs = { PALADIN_HOLY, PRIEST_DISCIPLINE, PRIEST_HOLY, PRIEST_SHADOW, SHAMAN_RESTORATION } },
            { name = "Enchant Helm - Hex of Leeching", itemId = 243949,
              qualities = { 243948, 243949 },
              specs = { PRIEST_HOLY } },
            { name = "Enchant Shoulders - Thalassian Recovery", itemId = 244018,
              qualities = { 244018, 244019 },
              specs = { PRIEST_HOLY } },
            { name = "Enchant Ring - Nature's Wrath", itemId = 243984,
              qualities = { 243984, 243985 },
              specs = { PRIEST_HOLY } },
            { name = "Enchant Helm - Blessing of Speed", itemId = 243979,
              qualities = { 243978, 243979 },
              specs = { PRIEST_SHADOW } },
            { name = "Enchant Shoulders - Flight of the Eagle", itemId = 243961,
              qualities = { 243960, 243961 },
              specs = { PRIEST_SHADOW } },
            { name = "Bright Linen Spellthread", itemId = 240156,
              qualities = { 240156, 240157 },
              specs = { PRIEST_SHADOW } },
            { name = "Enchant Ring - Thalassian Haste", itemId = 244010,
              qualities = { 244010, 244011 },
              specs = { PRIEST_SHADOW } },
            { name = "Enchant Ring - Amani Mastery", itemId = 243955,
              qualities = { 243954, 243955 },
              specs = { PRIEST_SHADOW } },
        },
    },
    ---------------------------------------------------------------------------
    -- Weapon Enchants
    ---------------------------------------------------------------------------
    {
        category = "Weapon Enchants",
        items = {
            { name = "Thalassian Phoenix Oil", itemId = 243733,
              qualities = { 243733, 243734 },
              specs = { DEATHKNIGHT_FROST_DK, DEATHKNIGHT_UNHOLY, DRUID_GUARDIAN, HUNTER_BEAST_MASTERY, HUNTER_MARKSMANSHIP, HUNTER_SURVIVAL, MAGE_ARCANE, MAGE_FIRE, ROGUE_SUBTLETY } },
        },
    },
    ---------------------------------------------------------------------------
    -- Other Gems
    ---------------------------------------------------------------------------
    {
        category = "Other Gems",
        items = {
            { name = "Flawless Deadly Peridot", itemId = 240890,
              qualities = { 240889, 240890 },
              specs = { DEMONHUNTER_VENGEANCE, DRUID_BALANCE, EVOKER_DEVASTATION, HUNTER_MARKSMANSHIP, MONK_WINDWALKER, PRIEST_DISCIPLINE, PRIEST_HOLY, ROGUE_ASSASSINATION, ROGUE_OUTLAW, SHAMAN_RESTORATION, WARLOCK_AFFLICTION, WARLOCK_DEMONOLOGY, WARLOCK_DESTRUCTION, WARRIOR_ARMS, WARRIOR_PROT } },
            { name = "Flawless Versatile Garnet", itemId = 240910,
              qualities = { 240909, 240910 },
              specs = { DEMONHUNTER_VENGEANCE, MONK_BREWMASTER, PRIEST_HOLY, SHAMAN_RESTORATION } },
        },
    },
}

ConsumableHelper.UtilityData = {
    ---------------------------------------------------------------------------
    -- Vantus Rune
    ---------------------------------------------------------------------------
    {
        category = "Vantus Rune",
        items = {
            { name = "Vantus Rune: Radiant", itemId = 245879,
              qualities = { 245879, 245880 } },
        },
    },
    ---------------------------------------------------------------------------
    -- Potions
    ---------------------------------------------------------------------------
    {
        category = "Potions",
        items = {
            { name = "Silvermoon Health Potion", itemId = 241304,
              qualities = { 241305, 241304 } },
            { name = "Lightfused Mana Potion", itemId = 241300,
              qualities = { 241300, 241301 } },
            { name = "Refreshing Serum", itemId = 241306,
              qualities = { 241306, 241307 } },
            { name = "Potion of Invisibility", itemId = 241302,
              qualities = { 241302, 241303 } },
            { name = "Slowfall Potion", itemId = 241338,
              qualities = { 241338, 241339 } },
        },
    },
    ---------------------------------------------------------------------------
    -- Useful Consumables
    ---------------------------------------------------------------------------
    {
        category = "Useful Consumables",
        items = {
            { name = "Auto Repair Hammer", itemId = 132514 },
            { name = "Void-Touched Drums", itemId = 244639 },
            { name = "Emergency Soul Link", itemId = 248486,
              qualities = { 248486, 269586 } },
        },
    },
}
